declare module 'react-native-ico-emojione-emojis' {
    import { ReactNode } from 'react';
    import { SvgProps, AdditionalProps } from 'react-native-svg';

    type iconNames = '1st-place-medal' |
      '2nd-place-medal' |
      '3rd-place-medal' |
      'a-button' |
      'ab-button' |
      'admission-tickets' |
      'aerial-tramway' |
      'airplane-arrival' |
      'airplane-departure' |
      'airplane' |
      'alarm-clock' |
      'alembic' |
      'alien-monster' |
      'alien' |
      'ambulance' |
      'american-football' |
      'amphora' |
      'anchor' |
      'anger-symbol' |
      'angry-face-with-horns' |
      'angry-face' |
      'anguished-face' |
      'ant' |
      'antenna-bars' |
      'anxious-face-with-sweat' |
      'aquarius' |
      'aries' |
      'articulated-lorry' |
      'artist-palette' |
      'asterisk' |
      'astonished-face' |
      'atm-sign' |
      'atom-symbol' |
      'automobile' |
      'avocado' |
      'b-button' |
      'baby-angel-dark-skin-tone' |
      'baby-angel-light-skin-tone' |
      'baby-angel-medium-dark-skin-tone' |
      'baby-angel-medium-light-skin-tone' |
      'baby-angel-medium-skin-tone' |
      'baby-angel' |
      'baby-bottle' |
      'baby-chick' |
      'baby-dark-skin-tone' |
      'baby-light-skin-tone' |
      'baby-medium-dark-skin-tone' |
      'baby-medium-light-skin-tone' |
      'baby-medium-skin-tone' |
      'baby-symbol' |
      'baby' |
      'back-arrow' |
      'backhand-index-pointing-down-dark-skin-tone' |
      'backhand-index-pointing-down-light-skin-tone' |
      'backhand-index-pointing-down-medium-dark-skin-tone' |
      'backhand-index-pointing-down-medium-light-skin-tone' |
      'backhand-index-pointing-down-medium-skin-tone' |
      'backhand-index-pointing-down' |
      'backhand-index-pointing-left-dark-skin-tone' |
      'backhand-index-pointing-left-light-skin-tone' |
      'backhand-index-pointing-left-medium-dark-skin-tone' |
      'backhand-index-pointing-left-medium-light-skin-tone' |
      'backhand-index-pointing-left-medium-skin-tone' |
      'backhand-index-pointing-left' |
      'backhand-index-pointing-right-dark-skin-tone' |
      'backhand-index-pointing-right-light-skin-tone' |
      'backhand-index-pointing-right-medium-dark-skin-tone' |
      'backhand-index-pointing-right-medium-light-skin-tone' |
      'backhand-index-pointing-right-medium-skin-tone' |
      'backhand-index-pointing-right' |
      'backhand-index-pointing-up-dark-skin-tone' |
      'backhand-index-pointing-up-light-skin-tone' |
      'backhand-index-pointing-up-medium-dark-skin-tone' |
      'backhand-index-pointing-up-medium-light-skin-tone' |
      'backhand-index-pointing-up-medium-skin-tone' |
      'backhand-index-pointing-up' |
      'backpack' |
      'bacon' |
      'badminton' |
      'baggage-claim' |
      'baguette-bread' |
      'balance-scale' |
      'balloon' |
      'ballot-box-with-ballot' |
      'ballot-box-with-check' |
      'banana' |
      'bank' |
      'bar-chart' |
      'barber-pole' |
      'baseball' |
      'basketball' |
      'bat' |
      'bathtub' |
      'battery' |
      'beach-with-umbrella' |
      'beaming-face-with-smiling-eyes' |
      'bear-face' |
      'beating-heart' |
      'bed' |
      'beer-mug' |
      'bell-with-slash' |
      'bell' |
      'bellhop-bell' |
      'bento-box' |
      'bicycle' |
      'bikini' |
      'biohazard' |
      'bird' |
      'birthday-cake' |
      'black-circle' |
      'black-heart' |
      'black-large-square' |
      'black-medium-small-square' |
      'black-medium-square' |
      'black-nib' |
      'black-small-square' |
      'black-square-button' |
      'blond-haired-person-dark-skin-tone' |
      'blond-haired-person-light-skin-tone' |
      'blond-haired-person-medium-dark-skin-tone' |
      'blond-haired-person-medium-light-skin-tone' |
      'blond-haired-person-medium-skin-tone' |
      'blond-haired-person' |
      'blossom' |
      'blowfish' |
      'blue-book' |
      'blue-circle' |
      'blue-heart' |
      'boar' |
      'bomb' |
      'bookmark-tabs' |
      'bookmark' |
      'books' |
      'bottle-with-popping-cork' |
      'bouquet' |
      'bow-and-arrow' |
      'bowling' |
      'boxing-glove' |
      'boy-dark-skin-tone' |
      'boy-light-skin-tone' |
      'boy-medium-dark-skin-tone' |
      'boy-medium-light-skin-tone' |
      'boy-medium-skin-tone' |
      'boy' |
      'bread' |
      'bride-with-veil-dark-skin-tone' |
      'bride-with-veil-light-skin-tone' |
      'bride-with-veil-medium-dark-skin-tone' |
      'bride-with-veil-medium-light-skin-tone' |
      'bride-with-veil-medium-skin-tone' |
      'bride-with-veil' |
      'bridge-at-night' |
      'briefcase' |
      'bright-button' |
      'broken-heart' |
      'bug' |
      'building-construction' |
      'bullet-train' |
      'burrito' |
      'bus-stop' |
      'bus' |
      'bust-in-silhouette' |
      'busts-in-silhouette' |
      'butterfly' |
      'cactus' |
      'calendar' |
      'call-me-hand-dark-skin-tone' |
      'call-me-hand-light-skin-tone' |
      'call-me-hand-medium-dark-skin-tone' |
      'call-me-hand-medium-light-skin-tone' |
      'call-me-hand-medium-skin-tone' |
      'call-me-hand' |
      'camel' |
      'camera-with-flash' |
      'camera' |
      'camping' |
      'cancer' |
      'candle' |
      'candy' |
      'canoe' |
      'capricorn' |
      'card-file-box' |
      'card-index-dividers' |
      'card-index' |
      'carousel-horse' |
      'carp-streamer' |
      'carrot' |
      'castle' |
      'cat-face-with-tears-of-joy' |
      'cat-face-with-wry-smile' |
      'cat-face' |
      'cat' |
      'chains' |
      'chart-decreasing' |
      'chart-increasing-with-yen' |
      'chart-increasing' |
      'cheese-wedge' |
      'cherries' |
      'cherry-blossom' |
      'chestnut' |
      'chicken' |
      'children-crossing' |
      'chipmunk' |
      'chocolate-bar' |
      'christmas-tree' |
      'church' |
      'cigarette' |
      'cinema' |
      'circled-m' |
      'circus-tent' |
      'cityscape-at-dusk' |
      'cityscape' |
      'cl-button' |
      'clamp' |
      'clapper-board' |
      'clapping-hands-dark-skin-tone' |
      'clapping-hands-light-skin-tone' |
      'clapping-hands-medium-dark-skin-tone' |
      'clapping-hands-medium-light-skin-tone' |
      'clapping-hands-medium-skin-tone' |
      'clapping-hands' |
      'classical-building' |
      'clinking-beer-mugs' |
      'clinking-glasses' |
      'clipboard' |
      'clockwise-vertical-arrows' |
      'closed-book' |
      'closed-mailbox-with-lowered-flag' |
      'closed-mailbox-with-raised-flag' |
      'closed-umbrella' |
      'cloud-with-lightning-and-rain' |
      'cloud-with-lightning' |
      'cloud-with-rain' |
      'cloud-with-snow' |
      'cloud' |
      'clown-face' |
      'club-suit' |
      'clutch-bag' |
      'cocktail-glass' |
      'coffin' |
      'collision' |
      'comet' |
      'computer-disk' |
      'computer-mouse' |
      'confetti-ball' |
      'confounded-face' |
      'confused-face' |
      'construction-worker-dark-skin-tone' |
      'construction-worker-light-skin-tone' |
      'construction-worker-medium-dark-skin-tone' |
      'construction-worker-medium-light-skin-tone' |
      'construction-worker-medium-skin-tone' |
      'construction-worker' |
      'construction' |
      'control-knobs' |
      'convenience-store' |
      'cooked-rice' |
      'cookie' |
      'cooking' |
      'cool-button' |
      'copyright' |
      'couch-and-lamp' |
      'counterclockwise-arrows-button' |
      'couple-with-heart-man-man' |
      'couple-with-heart-woman-woman' |
      'couple-with-heart' |
      'cow-face' |
      'cow' |
      'cowboy-hat-face' |
      'crab' |
      'crayon' |
      'credit-card' |
      'crescent-moon' |
      'cricket-game' |
      'crocodile' |
      'croissant' |
      'cross-mark-button' |
      'cross-mark' |
      'crossed-fingers-dark-skin-tone' |
      'crossed-fingers-light-skin-tone' |
      'crossed-fingers-medium-dark-skin-tone' |
      'crossed-fingers-medium-light-skin-tone' |
      'crossed-fingers-medium-skin-tone' |
      'crossed-fingers' |
      'crossed-swords' |
      'crown' |
      'crying-cat-face' |
      'crying-face' |
      'crystal-ball' |
      'cucumber' |
      'curly-loop' |
      'currency-exchange' |
      'curry-rice' |
      'custard' |
      'customs' |
      'cyclone' |
      'dagger' |
      'dango' |
      'dark-skin-tone' |
      'dashing-away' |
      'deciduous-tree' |
      'deer' |
      'delivery-truck' |
      'department-store' |
      'derelict-house' |
      'desert-island' |
      'desert' |
      'desktop-computer' |
      'detective-dark-skin-tone' |
      'detective-light-skin-tone' |
      'detective-medium-dark-skin-tone' |
      'detective-medium-light-skin-tone' |
      'detective-medium-skin-tone' |
      'detective' |
      'diamond-suit' |
      'diamond-with-a-dot' |
      'digit-eight' |
      'digit-five' |
      'digit-four' |
      'digit-nine' |
      'digit-one' |
      'digit-seven' |
      'digit-six' |
      'digit-three' |
      'digit-two' |
      'digit-zero' |
      'dim-button' |
      'direct-hit' |
      'disappointed-face' |
      'dizzy-face' |
      'dizzy' |
      'dog-face' |
      'dog' |
      'dollar-banknote' |
      'dolphin' |
      'door' |
      'dotted-six-pointed-star' |
      'double-curly-loop' |
      'double-exclamation-mark' |
      'doughnut' |
      'dove' |
      'down-arrow' |
      'down-left-arrow' |
      'down-right-arrow' |
      'downcast-face-with-sweat' |
      'downwards-button' |
      'dragon-face' |
      'dragon' |
      'dress' |
      'drooling-face' |
      'droplet' |
      'drum' |
      'duck' |
      'dvd' |
      'eagle' |
      'ear-dark-skin-tone' |
      'ear-light-skin-tone' |
      'ear-medium-dark-skin-tone' |
      'ear-medium-light-skin-tone' |
      'ear-medium-skin-tone' |
      'ear-of-corn' |
      'ear' |
      'egg' |
      'eggplant' |
      'eight-oclock' |
      'eight-pointed-star' |
      'eight-spoked-asterisk' |
      'eight-thirty' |
      'eject-button' |
      'electric-plug' |
      'elephant' |
      'eleven-oclock' |
      'eleven-thirty' |
      'end-arrow' |
      'envelope-with-arrow' |
      'envelope' |
      'euro-banknote' |
      'evergreen-tree' |
      'ewe' |
      'exclamation-mark' |
      'exclamation-question-mark' |
      'expressionless-face' |
      'eye-in-speech-bubble' |
      'eye' |
      'eyes' |
      'face-blowing-a-kiss' |
      'face-savoring-food' |
      'face-screaming-in-fear' |
      'face-with-head-bandage' |
      'face-with-medical-mask' |
      'face-with-open-mouth' |
      'face-with-rolling-eyes' |
      'face-with-steam-from-nose' |
      'face-with-tears-of-joy' |
      'face-with-thermometer' |
      'face-with-tongue' |
      'face-without-mouth' |
      'factory' |
      'fallen-leaf' |
      'family-man-man-boy-boy' |
      'family-man-man-boy' |
      'family-man-man-girl-boy' |
      'family-man-man-girl-girl' |
      'family-man-man-girl' |
      'family-man-woman-boy-boy' |
      'family-man-woman-girl-boy' |
      'family-man-woman-girl-girl' |
      'family-man-woman-girl' |
      'family-woman-woman-boy-boy' |
      'family-woman-woman-boy' |
      'family-woman-woman-girl-boy' |
      'family-woman-woman-girl-girl' |
      'family-woman-woman-girl' |
      'family' |
      'fast-down-button' |
      'fast-forward-button' |
      'fast-reverse-button' |
      'fast-up-button' |
      'fax-machine' |
      'fearful-face' |
      'ferris-wheel' |
      'ferry' |
      'field-hockey' |
      'file-cabinet' |
      'file-folder' |
      'film-frames' |
      'film-projector' |
      'fire-engine' |
      'fire' |
      'fireworks' |
      'first-quarter-moon-face' |
      'first-quarter-moon' |
      'fish-cake-with-swirl' |
      'fish' |
      'fishing-pole' |
      'five-oclock' |
      'five-thirty' |
      'flag-england' |
      'flag-for-afghanistan' |
      'flag-for-aland-islands' |
      'flag-for-albania' |
      'flag-for-algeria' |
      'flag-for-american-samoa' |
      'flag-for-andorra' |
      'flag-for-angola' |
      'flag-for-anguilla' |
      'flag-for-antarctica' |
      'flag-for-antigua-and-barbuda' |
      'flag-for-argentina' |
      'flag-for-armenia' |
      'flag-for-aruba' |
      'flag-for-ascension-island' |
      'flag-for-australia' |
      'flag-for-austria' |
      'flag-for-azerbaijan' |
      'flag-for-bahamas' |
      'flag-for-bahrain' |
      'flag-for-bangladesh' |
      'flag-for-barbados' |
      'flag-for-belarus' |
      'flag-for-belgium' |
      'flag-for-belize' |
      'flag-for-benin' |
      'flag-for-bermuda' |
      'flag-for-bhutan' |
      'flag-for-black-flag' |
      'flag-for-bolivia' |
      'flag-for-bosnia-and-herzegovina' |
      'flag-for-botswana' |
      'flag-for-bouvet-island' |
      'flag-for-brazil' |
      'flag-for-british-indian-ocean-territory' |
      'flag-for-british-virgin-islands' |
      'flag-for-brunei' |
      'flag-for-bulgaria' |
      'flag-for-burkina-faso' |
      'flag-for-burundi' |
      'flag-for-cambodia' |
      'flag-for-cameroon' |
      'flag-for-canada' |
      'flag-for-canary-islands' |
      'flag-for-cape-verde' |
      'flag-for-caribbean-netherlands' |
      'flag-for-cayman-islands' |
      'flag-for-central-african-republic' |
      'flag-for-ceuta-and-melilla' |
      'flag-for-chad' |
      'flag-for-chequered-flag' |
      'flag-for-chile' |
      'flag-for-china' |
      'flag-for-christmas-island' |
      'flag-for-clipperton-island' |
      'flag-for-cocos-islands' |
      'flag-for-colombia' |
      'flag-for-comoros' |
      'flag-for-congo-brazzaville' |
      'flag-for-congo-kinshasa' |
      'flag-for-cook-islands' |
      'flag-for-costa-rica' |
      'flag-for-cote-divoire' |
      'flag-for-croatia' |
      'flag-for-crossed-flags' |
      'flag-for-cuba' |
      'flag-for-curacao' |
      'flag-for-cyprus' |
      'flag-for-czechia' |
      'flag-for-denmark' |
      'flag-for-diego-garcia' |
      'flag-for-djibouti' |
      'flag-for-dominica' |
      'flag-for-dominican-republic' |
      'flag-for-ecuador' |
      'flag-for-egypt' |
      'flag-for-el-salvador' |
      'flag-for-equatorial-guinea' |
      'flag-for-eritrea' |
      'flag-for-estonia' |
      'flag-for-ethiopia' |
      'flag-for-european-union' |
      'flag-for-falkland-islands' |
      'flag-for-faroe-islands' |
      'flag-for-fiji' |
      'flag-for-finland' |
      'flag-for-france' |
      'flag-for-french-guiana' |
      'flag-for-french-polynesia' |
      'flag-for-french-southern-territories' |
      'flag-for-gabon' |
      'flag-for-gambia' |
      'flag-for-georgia' |
      'flag-for-germany' |
      'flag-for-ghana' |
      'flag-for-gibraltar' |
      'flag-for-greece' |
      'flag-for-greenland' |
      'flag-for-grenada' |
      'flag-for-guadeloupe' |
      'flag-for-guam' |
      'flag-for-guatemala' |
      'flag-for-guernsey' |
      'flag-for-guinea-bissau' |
      'flag-for-guinea' |
      'flag-for-guyana' |
      'flag-for-haiti' |
      'flag-for-heard-and-mcdonald-islands' |
      'flag-for-honduras' |
      'flag-for-hong-kong-sar-china' |
      'flag-for-hungary' |
      'flag-for-iceland' |
      'flag-for-india' |
      'flag-for-indonesia' |
      'flag-for-iran' |
      'flag-for-iraq' |
      'flag-for-ireland' |
      'flag-for-isle-of-man' |
      'flag-for-israel' |
      'flag-for-italy' |
      'flag-for-jamaica' |
      'flag-for-japan' |
      'flag-for-jersey' |
      'flag-for-jordan' |
      'flag-for-kazakhstan' |
      'flag-for-kenya' |
      'flag-for-kiribati' |
      'flag-for-kosovo' |
      'flag-for-kuwait' |
      'flag-for-kyrgyzstan' |
      'flag-for-laos' |
      'flag-for-latvia' |
      'flag-for-lebanon' |
      'flag-for-lesotho' |
      'flag-for-liberia' |
      'flag-for-libya' |
      'flag-for-liechtenstein' |
      'flag-for-lithuania' |
      'flag-for-luxembourg' |
      'flag-for-macau-sar-china' |
      'flag-for-macedonia' |
      'flag-for-madagascar' |
      'flag-for-malawi' |
      'flag-for-malaysia' |
      'flag-for-maldives' |
      'flag-for-mali' |
      'flag-for-malta' |
      'flag-for-marshall-islands' |
      'flag-for-martinique' |
      'flag-for-mauritania' |
      'flag-for-mauritius' |
      'flag-for-mayotte' |
      'flag-for-mexico' |
      'flag-for-micronesia' |
      'flag-for-moldova' |
      'flag-for-monaco' |
      'flag-for-mongolia' |
      'flag-for-montenegro' |
      'flag-for-montserrat' |
      'flag-for-morocco' |
      'flag-for-mozambique' |
      'flag-for-myanmar' |
      'flag-for-namibia' |
      'flag-for-nauru' |
      'flag-for-nepal' |
      'flag-for-netherlands' |
      'flag-for-new-caledonia' |
      'flag-for-new-zealand' |
      'flag-for-nicaragua' |
      'flag-for-niger' |
      'flag-for-nigeria' |
      'flag-for-niue' |
      'flag-for-norfolk-island' |
      'flag-for-north-korea' |
      'flag-for-northern-mariana-islands' |
      'flag-for-norway' |
      'flag-for-oman' |
      'flag-for-pakistan' |
      'flag-for-palau' |
      'flag-for-palestinian-territories' |
      'flag-for-panama' |
      'flag-for-papua-new-guinea' |
      'flag-for-paraguay' |
      'flag-for-peru' |
      'flag-for-philippines' |
      'flag-for-pitcairn-islands' |
      'flag-for-poland' |
      'flag-for-portugal' |
      'flag-for-puerto-rico' |
      'flag-for-qatar' |
      'flag-for-rainbow-flag' |
      'flag-for-reunion' |
      'flag-for-romania' |
      'flag-for-russia' |
      'flag-for-rwanda' |
      'flag-for-samoa' |
      'flag-for-san-marino' |
      'flag-for-sao-tome-and-principe' |
      'flag-for-saudi-arabia' |
      'flag-for-senegal' |
      'flag-for-serbia' |
      'flag-for-seychelles' |
      'flag-for-sierra-leone' |
      'flag-for-singapore' |
      'flag-for-sint-maarten' |
      'flag-for-slovakia' |
      'flag-for-slovenia' |
      'flag-for-solomon-islands' |
      'flag-for-somalia' |
      'flag-for-south-africa' |
      'flag-for-south-georgia-and-south-sandwich-islands' |
      'flag-for-south-korea' |
      'flag-for-south-sudan' |
      'flag-for-spain' |
      'flag-for-sri-lanka' |
      'flag-for-st-barthelemy' |
      'flag-for-st-helena' |
      'flag-for-st-kitts-and-nevis' |
      'flag-for-st-lucia' |
      'flag-for-st-martin' |
      'flag-for-st-pierre-and-miquelon' |
      'flag-for-st-vincent-and-grenadines' |
      'flag-for-sudan' |
      'flag-for-suriname' |
      'flag-for-svalbard-and-jan-mayen' |
      'flag-for-swaziland' |
      'flag-for-sweden' |
      'flag-for-switzerland' |
      'flag-for-syria' |
      'flag-for-taiwan' |
      'flag-for-tajikistan' |
      'flag-for-tanzania' |
      'flag-for-thailand' |
      'flag-for-timor-leste' |
      'flag-for-togo' |
      'flag-for-tokelau' |
      'flag-for-tonga' |
      'flag-for-triangular-flag' |
      'flag-for-trinidad-and-tobago' |
      'flag-for-tristan-da-cunha' |
      'flag-for-tunisia' |
      'flag-for-turkey' |
      'flag-for-turkmenistan' |
      'flag-for-turks-and-caicos-islands' |
      'flag-for-tuvalu' |
      'flag-for-uganda' |
      'flag-for-ukraine' |
      'flag-for-united-arab-emirates' |
      'flag-for-united-kingdom' |
      'flag-for-united-states' |
      'flag-for-uruguay' |
      'flag-for-us-outlying-islands' |
      'flag-for-us-virgin-islands' |
      'flag-for-uzbekistan' |
      'flag-for-vanuatu' |
      'flag-for-vatican-city' |
      'flag-for-venezuela' |
      'flag-for-vietnam' |
      'flag-for-wallis-and-futuna' |
      'flag-for-western-sahara' |
      'flag-for-white-flag' |
      'flag-for-yemen' |
      'flag-for-zambia' |
      'flag-for-zimbabwe' |
      'flag-in-hole' |
      'flag-scotland' |
      'flashlight' |
      'fleur-de-lis' |
      'flexed-biceps-dark-skin-tone' |
      'flexed-biceps-light-skin-tone' |
      'flexed-biceps-medium-dark-skin-tone' |
      'flexed-biceps-medium-light-skin-tone' |
      'flexed-biceps-medium-skin-tone' |
      'flexed-biceps' |
      'floppy-disk' |
      'flower-playing-cards' |
      'flushed-face' |
      'fog' |
      'foggy' |
      'folded-hands-dark-skin-tone' |
      'folded-hands-light-skin-tone' |
      'folded-hands-medium-dark-skin-tone' |
      'folded-hands-medium-light-skin-tone' |
      'folded-hands-medium-skin-tone' |
      'folded-hands' |
      'footprints' |
      'fork-and-knife-with-plate' |
      'fork-and-knife' |
      'fountain-pen' |
      'fountain' |
      'four-leaf-clover' |
      'four-oclock' |
      'four-thirty' |
      'fox' |
      'framed-picture' |
      'free-button' |
      'french-fries' |
      'fried-shrimp' |
      'frog-face' |
      'front-facing-baby-chick' |
      'frowning-face-with-open-mouth' |
      'frowning-face' |
      'fuel-pump' |
      'full-moon-face' |
      'full-moon' |
      'funeral-urn' |
      'game-die' |
      'gear' |
      'gem-stone' |
      'gemini' |
      'ghost' |
      'girl-dark-skin-tone' |
      'girl-light-skin-tone' |
      'girl-medium-dark-skin-tone' |
      'girl-medium-light-skin-tone' |
      'girl-medium-skin-tone' |
      'girl' |
      'glass-of-milk' |
      'glasses' |
      'globe-showing-americas' |
      'globe-showing-asia-australia' |
      'globe-showing-europe-africa' |
      'globe-with-meridians' |
      'glowing-star' |
      'goal-net' |
      'goat' |
      'goblin' |
      'gorilla' |
      'graduation-cap' |
      'grapes' |
      'green-apple' |
      'green-book' |
      'green-heart' |
      'green-salad' |
      'grimacing-face' |
      'grinning-cat-face-with-smiling-eyes' |
      'grinning-cat-face' |
      'grinning-face-with-big-eyes' |
      'grinning-face-with-smiling-eyes' |
      'grinning-face-with-sweat' |
      'grinning-face' |
      'grinning-squinting-face' |
      'growing-heart' |
      'guard-dark-skin-tone' |
      'guard-light-skin-tone' |
      'guard-medium-dark-skin-tone' |
      'guard-medium-light-skin-tone' |
      'guard-medium-skin-tone' |
      'guard' |
      'guitar' |
      'hamburger' |
      'hammer-and-pick' |
      'hammer-and-wrench' |
      'hammer' |
      'hamster-face' |
      'hand-with-fingers-splayed-dark-skin-tone' |
      'hand-with-fingers-splayed-light-skin-tone' |
      'hand-with-fingers-splayed-medium-dark-skin-tone' |
      'hand-with-fingers-splayed-medium-light-skin-tone' |
      'hand-with-fingers-splayed-medium-skin-tone' |
      'hand-with-fingers-splayed' |
      'handbag' |
      'handshake-dark-skin-tone' |
      'handshake-light-skin-tone' |
      'handshake-medium-dark-skin-tone' |
      'handshake-medium-light-skin-tone' |
      'handshake-medium-skin-tone' |
      'handshake' |
      'hatching-chick' |
      'headphone' |
      'hear-no-evil-monkey' |
      'heart-decoration' |
      'heart-suit' |
      'heart-with-arrow' |
      'heart-with-ribbon' |
      'heavy-check-mark' |
      'heavy-division-sign' |
      'heavy-dollar-sign' |
      'heavy-heart-exclamation' |
      'heavy-large-circle' |
      'heavy-minus-sign' |
      'heavy-plus-sign' |
      'helicopter' |
      'herb' |
      'hibiscus' |
      'high-heeled-shoe' |
      'high-speed-train' |
      'high-voltage' |
      'hole' |
      'honey-pot' |
      'honeybee' |
      'horizontal-traffic-light' |
      'horse-face' |
      'horse-racing-dark-skin-tone' |
      'horse-racing-light-skin-tone' |
      'horse-racing-medium-dark-skin-tone' |
      'horse-racing-medium-light-skin-tone' |
      'horse-racing-medium-skin-tone' |
      'horse-racing' |
      'horse' |
      'hospital' |
      'hot-beverage' |
      'hot-dog' |
      'hot-pepper' |
      'hot-springs' |
      'hotel' |
      'hourglass-done' |
      'hourglass-not-done' |
      'house-with-garden' |
      'house' |
      'houses' |
      'hugging-face' |
      'hundred-points' |
      'hushed-face' |
      'ice-cream' |
      'ice-hockey' |
      'ice-skate' |
      'id-button' |
      'inbox-tray' |
      'incoming-envelope' |
      'index-pointing-up-dark-skin-tone' |
      'index-pointing-up-light-skin-tone' |
      'index-pointing-up-medium-dark-skin-tone' |
      'index-pointing-up-medium-light-skin-tone' |
      'index-pointing-up-medium-skin-tone' |
      'index-pointing-up' |
      'information' |
      'input-latin-letters' |
      'input-latin-lowercase' |
      'input-latin-uppercase' |
      'input-numbers' |
      'input-symbols' |
      'jack-o-lantern' |
      'japanese-acceptable-button' |
      'japanese-application-button' |
      'japanese-bargain-button' |
      'japanese-castle' |
      'japanese-congratulations-button' |
      'japanese-discount-button' |
      'japanese-dolls' |
      'japanese-free-of-charge-button' |
      'japanese-here-button' |
      'japanese-monthly-amount-button' |
      'japanese-no-vacancy-button' |
      'japanese-not-free-of-charge-button' |
      'japanese-open-for-business-button' |
      'japanese-passing-grade-button' |
      'japanese-post-office' |
      'japanese-prohibited-button' |
      'japanese-reserved-button' |
      'japanese-secret-button' |
      'japanese-service-charge-button' |
      'japanese-symbol-for-beginner' |
      'japanese-vacancy-button' |
      'jeans' |
      'joker' |
      'joystick' |
      'kaaba' |
      'key' |
      'keyboard' |
      'keycap-0' |
      'keycap-1' |
      'keycap-10' |
      'keycap-2' |
      'keycap-3' |
      'keycap-4' |
      'keycap-5' |
      'keycap-6' |
      'keycap-7' |
      'keycap-8' |
      'keycap-9' |
      'keycap-asterisk' |
      'keycap-pound' |
      'kick-scooter' |
      'kimono' |
      'kiss-man-man' |
      'kiss-mark' |
      'kiss-woman-woman' |
      'kiss' |
      'kissing-cat-face' |
      'kissing-face-with-closed-eyes' |
      'kissing-face-with-smiling-eyes' |
      'kissing-face' |
      'kitchen-knife' |
      'kiwi-fruit' |
      'koala' |
      'label' |
      'lady-beetle' |
      'laptop-computer' |
      'large-blue-diamond' |
      'large-orange-diamond' |
      'last-quarter-moon-face' |
      'last-quarter-moon' |
      'last-track-button' |
      'latin-cross' |
      'leaf-fluttering-in-wind' |
      'ledger' |
      'left-arrow-curving-right' |
      'left-arrow' |
      'left-facing-fist-dark-skin-tone' |
      'left-facing-fist-light-skin-tone' |
      'left-facing-fist-medium-dark-skin-tone' |
      'left-facing-fist-medium-light-skin-tone' |
      'left-facing-fist-medium-skin-tone' |
      'left-facing-fist' |
      'left-luggage' |
      'left-right-arrow' |
      'left-speech-bubble' |
      'lemon' |
      'leo' |
      'leopard' |
      'letter-a' |
      'letter-b' |
      'letter-c' |
      'letter-d' |
      'letter-e' |
      'letter-f' |
      'letter-g' |
      'letter-h' |
      'letter-i' |
      'letter-j' |
      'letter-k' |
      'letter-l' |
      'letter-m' |
      'letter-n' |
      'letter-o' |
      'letter-p' |
      'letter-q' |
      'letter-r' |
      'letter-s' |
      'letter-t' |
      'letter-u' |
      'letter-v' |
      'letter-w' |
      'letter-x' |
      'letter-y' |
      'letter-z' |
      'level-slider' |
      'libra' |
      'light-bulb' |
      'light-rail' |
      'light-skin-tone' |
      'link' |
      'linked-paperclips' |
      'lion-face' |
      'lipstick' |
      'litter-in-bin-sign' |
      'lizard' |
      'locked-with-key' |
      'locked-with-pen' |
      'locked' |
      'locomotive' |
      'lollipop' |
      'loudly-crying-face' |
      'loudspeaker' |
      'love-hotel' |
      'love-letter' |
      'lying-face' |
      'magnifying-glass-tilted-left' |
      'magnifying-glass-tilted-right' |
      'mahjong-red-dragon' |
      'man-and-woman-holding-hands' |
      'man-dancing-dark-skin-tone' |
      'man-dancing-light-skin-tone' |
      'man-dancing-medium-dark-skin-tone' |
      'man-dancing-medium-light-skin-tone' |
      'man-dancing-medium-skin-tone' |
      'man-dancing' |
      'man-dark-skin-tone' |
      'man-in-suit-levitating' |
      'man-in-tuxedo-dark-skin-tone' |
      'man-in-tuxedo-light-skin-tone' |
      'man-in-tuxedo-medium-dark-skin-tone' |
      'man-in-tuxedo-medium-light-skin-tone' |
      'man-in-tuxedo-medium-skin-tone' |
      'man-in-tuxedo' |
      'man-light-skin-tone' |
      'man-medium-dark-skin-tone' |
      'man-medium-light-skin-tone' |
      'man-medium-skin-tone' |
      'man-with-chinese-cap-dark-skin-tone' |
      'man-with-chinese-cap-light-skin-tone' |
      'man-with-chinese-cap-medium-dark-skin-tone' |
      'man-with-chinese-cap-medium-light-skin-tone' |
      'man-with-chinese-cap-medium-skin-tone' |
      'man-with-chinese-cap' |
      'man' |
      'mans-shoe' |
      'mantelpiece-clock' |
      'map-of-japan' |
      'maple-leaf' |
      'martial-arts-uniform' |
      'meat-on-bone' |
      'medium-dark-skin-tone' |
      'medium-light-skin-tone' |
      'medium-skin-tone' |
      'megaphone' |
      'melon' |
      'memo' |
      'menorah' |
      'mens-room' |
      'metro' |
      'microphone' |
      'microscope' |
      'middle-finger-dark-skin-tone' |
      'middle-finger-light-skin-tone' |
      'middle-finger-medium-dark-skin-tone' |
      'middle-finger-medium-light-skin-tone' |
      'middle-finger-medium-skin-tone' |
      'middle-finger' |
      'military-medal' |
      'milky-way' |
      'minibus' |
      'moai' |
      'mobile-phone-off' |
      'mobile-phone-with-arrow' |
      'mobile-phone' |
      'money-bag' |
      'money-mouth-face' |
      'money-with-wings' |
      'monkey-face' |
      'monkey' |
      'monorail' |
      'moon-viewing-ceremony' |
      'mosque' |
      'motor-boat' |
      'motor-scooter' |
      'motorcycle' |
      'motorway' |
      'mount-fuji' |
      'mountain-cableway' |
      'mountain-railway' |
      'mountain' |
      'mouse-face' |
      'mouse' |
      'mouth' |
      'movie-camera' |
      'mrs-claus-dark-skin-tone' |
      'mrs-claus-light-skin-tone' |
      'mrs-claus-medium-dark-skin-tone' |
      'mrs-claus-medium-light-skin-tone' |
      'mrs-claus-medium-skin-tone' |
      'mrs-claus' |
      'mushroom' |
      'musical-keyboard' |
      'musical-note' |
      'musical-notes' |
      'musical-score' |
      'muted-speaker' |
      'nail-polish-dark-skin-tone' |
      'nail-polish-light-skin-tone' |
      'nail-polish-medium-dark-skin-tone' |
      'nail-polish-medium-light-skin-tone' |
      'nail-polish-medium-skin-tone' |
      'nail-polish' |
      'name-badge' |
      'national-park' |
      'nauseated-face' |
      'necktie' |
      'nerd-face' |
      'neutral-face' |
      'new-button' |
      'new-moon-face' |
      'new-moon' |
      'newspaper' |
      'next-track-button' |
      'ng-button' |
      'night-with-stars' |
      'nine-oclock' |
      'nine-thirty' |
      'no-bicycles' |
      'no-entry' |
      'no-littering' |
      'no-mobile-phones' |
      'no-one-under-eighteen' |
      'no-pedestrians' |
      'no-smoking' |
      'non-potable-water' |
      'nose-dark-skin-tone' |
      'nose-light-skin-tone' |
      'nose-medium-dark-skin-tone' |
      'nose-medium-light-skin-tone' |
      'nose-medium-skin-tone' |
      'nose' |
      'notebook-with-decorative-cover' |
      'notebook' |
      'nut-and-bolt' |
      'o-button' |
      'octopus' |
      'oden' |
      'office-building' |
      'ogre' |
      'oil-drum' |
      'ok-button' |
      'ok-hand-dark-skin-tone' |
      'ok-hand-light-skin-tone' |
      'ok-hand-medium-dark-skin-tone' |
      'ok-hand-medium-light-skin-tone' |
      'ok-hand-medium-skin-tone' |
      'ok-hand' |
      'old-key' |
      'old-man-dark-skin-tone' |
      'old-man-light-skin-tone' |
      'old-man-medium-dark-skin-tone' |
      'old-man-medium-light-skin-tone' |
      'old-man-medium-skin-tone' |
      'old-man' |
      'old-woman-dark-skin-tone' |
      'old-woman-light-skin-tone' |
      'old-woman-medium-dark-skin-tone' |
      'old-woman-medium-light-skin-tone' |
      'old-woman-medium-skin-tone' |
      'old-woman' |
      'om' |
      'on-arrow' |
      'oncoming-automobile' |
      'oncoming-bus' |
      'oncoming-fist-dark-skin-tone' |
      'oncoming-fist-light-skin-tone' |
      'oncoming-fist-medium-dark-skin-tone' |
      'oncoming-fist-medium-light-skin-tone' |
      'oncoming-fist-medium-skin-tone' |
      'oncoming-fist' |
      'oncoming-police-car' |
      'oncoming-taxi' |
      'one-oclock' |
      'one-thirty' |
      'open-book' |
      'open-file-folder' |
      'open-hands-dark-skin-tone' |
      'open-hands-light-skin-tone' |
      'open-hands-medium-dark-skin-tone' |
      'open-hands-medium-light-skin-tone' |
      'open-hands-medium-skin-tone' |
      'open-hands' |
      'open-mailbox-with-lowered-flag' |
      'open-mailbox-with-raised-flag' |
      'ophiuchus' |
      'optical-disk' |
      'orange-book' |
      'orthodox-cross' |
      'outbox-tray' |
      'owl' |
      'ox' |
      'p-button' |
      'package' |
      'page-facing-up' |
      'page-with-curl' |
      'pager' |
      'paintbrush' |
      'palm-tree' |
      'pancakes' |
      'panda-face' |
      'paperclip' |
      'part-alternation-mark' |
      'party-popper' |
      'passenger-ship' |
      'passport-control' |
      'pause-button' |
      'paw-prints' |
      'peace-symbol' |
      'peach' |
      'peanuts' |
      'pear' |
      'pen' |
      'pencil' |
      'penguin' |
      'pensive-face' |
      'people-with-bunny-ears' |
      'people-wrestling-dark-skin-tone' |
      'people-wrestling-light-skin-tone' |
      'people-wrestling-medium-dark-skin-tone' |
      'people-wrestling-medium-light-skin-tone' |
      'people-wrestling-medium-skin-tone' |
      'people-wrestling' |
      'performing-arts' |
      'persevering-face' |
      'person-biking-dark-skin-tone' |
      'person-biking-light-skin-tone' |
      'person-biking-medium-dark-skin-tone' |
      'person-biking-medium-light-skin-tone' |
      'person-biking-medium-skin-tone' |
      'person-biking' |
      'person-bouncing-ball-dark-skin-tone' |
      'person-bouncing-ball-light-skin-tone' |
      'person-bouncing-ball-medium-dark-skin-tone' |
      'person-bouncing-ball-medium-light-skin-tone' |
      'person-bouncing-ball-medium-skin-tone' |
      'person-bouncing-ball' |
      'person-bowing-dark-skin-tone' |
      'person-bowing-light-skin-tone' |
      'person-bowing-medium-dark-skin-tone' |
      'person-bowing-medium-light-skin-tone' |
      'person-bowing-medium-skin-tone' |
      'person-bowing' |
      'person-cartwheeling-dark-skin-tone' |
      'person-cartwheeling-light-skin-tone' |
      'person-cartwheeling-medium-dark-skin-tone' |
      'person-cartwheeling-medium-light-skin-tone' |
      'person-cartwheeling-medium-skin-tone' |
      'person-cartwheeling' |
      'person-facepalming-dark-skin-tone' |
      'person-facepalming-light-skin-tone' |
      'person-facepalming-medium-dark-skin-tone' |
      'person-facepalming-medium-light-skin-tone' |
      'person-facepalming-medium-skin-tone' |
      'person-facepalming' |
      'person-fencing' |
      'person-frowning-dark-skin-tone' |
      'person-frowning-light-skin-tone' |
      'person-frowning-medium-dark-skin-tone' |
      'person-frowning-medium-light-skin-tone' |
      'person-frowning-medium-skin-tone' |
      'person-frowning' |
      'person-gesturing-no-dark-skin-tone' |
      'person-gesturing-no-light-skin-tone' |
      'person-gesturing-no-medium-dark-skin-tone' |
      'person-gesturing-no-medium-light-skin-tone' |
      'person-gesturing-no-medium-skin-tone' |
      'person-gesturing-no' |
      'person-gesturing-ok-dark-skin-tone' |
      'person-gesturing-ok-light-skin-tone' |
      'person-gesturing-ok-medium-dark-skin-tone' |
      'person-gesturing-ok-medium-light-skin-tone' |
      'person-gesturing-ok-medium-skin-tone' |
      'person-gesturing-ok' |
      'person-getting-haircut-dark-skin-tone' |
      'person-getting-haircut-light-skin-tone' |
      'person-getting-haircut-medium-dark-skin-tone' |
      'person-getting-haircut-medium-light-skin-tone' |
      'person-getting-haircut-medium-skin-tone' |
      'person-getting-haircut' |
      'person-getting-massage-dark-skin-tone' |
      'person-getting-massage-light-skin-tone' |
      'person-getting-massage-medium-dark-skin-tone' |
      'person-getting-massage-medium-light-skin-tone' |
      'person-getting-massage-medium-skin-tone' |
      'person-getting-massage' |
      'person-golfing' |
      'person-in-bed' |
      'person-juggling-dark-skin-tone' |
      'person-juggling-light-skin-tone' |
      'person-juggling-medium-dark-skin-tone' |
      'person-juggling-medium-light-skin-tone' |
      'person-juggling-medium-skin-tone' |
      'person-juggling' |
      'person-lifting-weights-dark-skin-tone' |
      'person-lifting-weights-light-skin-tone' |
      'person-lifting-weights-medium-dark-skin-tone' |
      'person-lifting-weights-medium-light-skin-tone' |
      'person-lifting-weights-medium-skin-tone' |
      'person-lifting-weights' |
      'person-mountain-biking-dark-skin-tone' |
      'person-mountain-biking-light-skin-tone' |
      'person-mountain-biking-medium-dark-skin-tone' |
      'person-mountain-biking-medium-light-skin-tone' |
      'person-mountain-biking-medium-skin-tone' |
      'person-mountain-biking' |
      'person-playing-handball-dark-skin-tone' |
      'person-playing-handball-light-skin-tone' |
      'person-playing-handball-medium-dark-skin-tone' |
      'person-playing-handball-medium-light-skin-tone' |
      'person-playing-handball-medium-skin-tone' |
      'person-playing-handball' |
      'person-playing-water-polo-dark-skin-tone' |
      'person-playing-water-polo-light-skin-tone' |
      'person-playing-water-polo-medium-dark-skin-tone' |
      'person-playing-water-polo-medium-light-skin-tone' |
      'person-playing-water-polo-medium-skin-tone' |
      'person-playing-water-polo' |
      'person-pouting-dark-skin-tone' |
      'person-pouting-light-skin-tone' |
      'person-pouting-medium-dark-skin-tone' |
      'person-pouting-medium-light-skin-tone' |
      'person-pouting-medium-skin-tone' |
      'person-pouting' |
      'person-raising-hand-dark-skin-tone' |
      'person-raising-hand-light-skin-tone' |
      'person-raising-hand-medium-dark-skin-tone' |
      'person-raising-hand-medium-light-skin-tone' |
      'person-raising-hand-medium-skin-tone' |
      'person-raising-hand' |
      'person-rowing-boat-dark-skin-tone' |
      'person-rowing-boat-light-skin-tone' |
      'person-rowing-boat-medium-dark-skin-tone' |
      'person-rowing-boat-medium-light-skin-tone' |
      'person-rowing-boat-medium-skin-tone' |
      'person-rowing-boat' |
      'person-running-dark-skin-tone' |
      'person-running-light-skin-tone' |
      'person-running-medium-dark-skin-tone' |
      'person-running-medium-light-skin-tone' |
      'person-running-medium-skin-tone' |
      'person-running' |
      'person-shrugging-dark-skin-tone' |
      'person-shrugging-light-skin-tone' |
      'person-shrugging-medium-dark-skin-tone' |
      'person-shrugging-medium-light-skin-tone' |
      'person-shrugging-medium-skin-tone' |
      'person-shrugging' |
      'person-surfing-dark-skin-tone' |
      'person-surfing-light-skin-tone' |
      'person-surfing-medium-dark-skin-tone' |
      'person-surfing-medium-light-skin-tone' |
      'person-surfing-medium-skin-tone' |
      'person-surfing' |
      'person-swimming-dark-skin-tone' |
      'person-swimming-light-skin-tone' |
      'person-swimming-medium-dark-skin-tone' |
      'person-swimming-medium-light-skin-tone' |
      'person-swimming-medium-skin-tone' |
      'person-swimming' |
      'person-taking-bath-dark-skin-tone' |
      'person-taking-bath-light-skin-tone' |
      'person-taking-bath-medium-dark-skin-tone' |
      'person-taking-bath-medium-light-skin-tone' |
      'person-taking-bath-medium-skin-tone' |
      'person-taking-bath' |
      'person-tipping-hand-dark-skin-tone' |
      'person-tipping-hand-light-skin-tone' |
      'person-tipping-hand-medium-dark-skin-tone' |
      'person-tipping-hand-medium-light-skin-tone' |
      'person-tipping-hand-medium-skin-tone' |
      'person-tipping-hand' |
      'person-walking-dark-skin-tone' |
      'person-walking-light-skin-tone' |
      'person-walking-medium-dark-skin-tone' |
      'person-walking-medium-light-skin-tone' |
      'person-walking-medium-skin-tone' |
      'person-walking' |
      'person-wearing-turban-dark-skin-tone' |
      'person-wearing-turban-light-skin-tone' |
      'person-wearing-turban-medium-dark-skin-tone' |
      'person-wearing-turban-medium-light-skin-tone' |
      'person-wearing-turban-medium-skin-tone' |
      'person-wearing-turban' |
      'pick' |
      'pig-face' |
      'pig-nose' |
      'pig' |
      'pile-of-poo' |
      'pill' |
      'pine-decoration' |
      'pineapple' |
      'ping-pong' |
      'pisces' |
      'pistol' |
      'pizza' |
      'place-of-worship' |
      'play-button' |
      'play-or-pause-button' |
      'police-car-light' |
      'police-car' |
      'police-officer-dark-skin-tone' |
      'police-officer-light-skin-tone' |
      'police-officer-medium-dark-skin-tone' |
      'police-officer-medium-light-skin-tone' |
      'police-officer-medium-skin-tone' |
      'police-officer' |
      'poodle' |
      'pool-8-ball' |
      'popcorn' |
      'post-office' |
      'postal-horn' |
      'postbox' |
      'pot-of-food' |
      'potable-water' |
      'potato' |
      'poultry-leg' |
      'pound-banknote' |
      'pound-symbol' |
      'pouting-cat-face' |
      'pouting-face' |
      'prayer-beads' |
      'pregnant-woman-dark-skin-tone' |
      'pregnant-woman-light-skin-tone' |
      'pregnant-woman-medium-dark-skin-tone' |
      'pregnant-woman-medium-light-skin-tone' |
      'pregnant-woman-medium-skin-tone' |
      'pregnant-woman' |
      'prince-dark-skin-tone' |
      'prince-light-skin-tone' |
      'prince-medium-dark-skin-tone' |
      'prince-medium-light-skin-tone' |
      'prince-medium-skin-tone' |
      'prince' |
      'princess-dark-skin-tone' |
      'princess-light-skin-tone' |
      'princess-medium-dark-skin-tone' |
      'princess-medium-light-skin-tone' |
      'princess-medium-skin-tone' |
      'princess' |
      'printer' |
      'prohibited' |
      'purple-heart' |
      'purse' |
      'pushpin' |
      'question-mark' |
      'rabbit-face' |
      'rabbit' |
      'racing-car' |
      'radio-button' |
      'radio' |
      'radioactive' |
      'railway-car' |
      'railway-track' |
      'rainbow' |
      'raised-back-of-hand-dark-skin-tone' |
      'raised-back-of-hand-light-skin-tone' |
      'raised-back-of-hand-medium-dark-skin-tone' |
      'raised-back-of-hand-medium-light-skin-tone' |
      'raised-back-of-hand-medium-skin-tone' |
      'raised-back-of-hand' |
      'raised-fist-dark-skin-tone' |
      'raised-fist-light-skin-tone' |
      'raised-fist-medium-dark-skin-tone' |
      'raised-fist-medium-light-skin-tone' |
      'raised-fist-medium-skin-tone' |
      'raised-fist' |
      'raised-hand-dark-skin-tone' |
      'raised-hand-light-skin-tone' |
      'raised-hand-medium-dark-skin-tone' |
      'raised-hand-medium-light-skin-tone' |
      'raised-hand-medium-skin-tone' |
      'raised-hand' |
      'raising-hands-dark-skin-tone' |
      'raising-hands-light-skin-tone' |
      'raising-hands-medium-dark-skin-tone' |
      'raising-hands-medium-light-skin-tone' |
      'raising-hands-medium-skin-tone' |
      'raising-hands' |
      'ram' |
      'rat' |
      'record-button' |
      'recycling-symbol' |
      'red-apple' |
      'red-circle' |
      'red-heart' |
      'red-paper-lantern' |
      'red-triangle-pointed-down' |
      'red-triangle-pointed-up' |
      'registered' |
      'relieved-face' |
      'reminder-ribbon' |
      'repeat-button' |
      'repeat-single-button' |
      'rescue-workers-helmet' |
      'restroom' |
      'reverse-button' |
      'revolving-hearts' |
      'rhinoceros' |
      'ribbon' |
      'rice-ball' |
      'rice-cracker' |
      'right-anger-bubble' |
      'right-arrow-curving-down' |
      'right-arrow-curving-left' |
      'right-arrow-curving-up' |
      'right-arrow' |
      'right-facing-fist-dark-skin-tone' |
      'right-facing-fist-light-skin-tone' |
      'right-facing-fist-medium-dark-skin-tone' |
      'right-facing-fist-medium-light-skin-tone' |
      'right-facing-fist-medium-skin-tone' |
      'right-facing-fist' |
      'ring' |
      'roasted-sweet-potato' |
      'robot-face' |
      'rocket' |
      'rolled-up-newspaper' |
      'roller-coaster' |
      'rolling-on-the-floor-laughing' |
      'rooster' |
      'rose' |
      'rosette' |
      'round-pushpin' |
      'rugby-football' |
      'running-shirt' |
      'running-shoe' |
      'sad-but-relieved-face' |
      'sagittarius' |
      'sailboat' |
      'sake' |
      'santa-claus-dark-skin-tone' |
      'santa-claus-light-skin-tone' |
      'santa-claus-medium-dark-skin-tone' |
      'santa-claus-medium-light-skin-tone' |
      'santa-claus-medium-skin-tone' |
      'santa-claus' |
      'satellite-antenna' |
      'satellite' |
      'saxophone' |
      'school' |
      'scissors' |
      'scorpio' |
      'scorpion' |
      'scroll' |
      'seat' |
      'see-no-evil-monkey' |
      'seedling' |
      'selfie-dark-skin-tone' |
      'selfie-light-skin-tone' |
      'selfie-medium-dark-skin-tone' |
      'selfie-medium-light-skin-tone' |
      'selfie-medium-skin-tone' |
      'selfie' |
      'seven-oclock' |
      'seven-thirty' |
      'shallow-pan-of-food' |
      'shamrock' |
      'shark' |
      'shaved-ice' |
      'sheaf-of-rice' |
      'shield' |
      'shinto-shrine' |
      'ship' |
      'shooting-star' |
      'shopping-bags' |
      'shopping-cart' |
      'shortcake' |
      'shower' |
      'shrimp' |
      'shuffle-tracks-button' |
      'sign-of-the-horns-dark-skin-tone' |
      'sign-of-the-horns-light-skin-tone' |
      'sign-of-the-horns-medium-dark-skin-tone' |
      'sign-of-the-horns-medium-light-skin-tone' |
      'sign-of-the-horns-medium-skin-tone' |
      'sign-of-the-horns' |
      'six-oclock' |
      'six-thirty' |
      'skier' |
      'skis' |
      'skull-and-crossbones' |
      'skull' |
      'sleeping-face' |
      'sleepy-face' |
      'slightly-frowning-face' |
      'slightly-smiling-face' |
      'slot-machine' |
      'small-airplane' |
      'small-blue-diamond' |
      'small-orange-diamond' |
      'smiling-cat-face-with-heart-eyes' |
      'smiling-face-with-halo' |
      'smiling-face-with-heart-eyes' |
      'smiling-face-with-horns' |
      'smiling-face-with-smiling-eyes' |
      'smiling-face-with-sunglasses' |
      'smiling-face' |
      'smirking-face' |
      'snail' |
      'snake' |
      'sneezing-face' |
      'snow-capped-mountain' |
      'snowboarder' |
      'snowflake' |
      'snowman-without-snow' |
      'snowman' |
      'soccer-ball' |
      'soft-ice-cream' |
      'soon-arrow' |
      'sos-button' |
      'spade-suit' |
      'spaghetti' |
      'sparkle' |
      'sparkler' |
      'sparkles' |
      'sparkling-heart' |
      'speak-no-evil-monkey' |
      'speaker-high-volume' |
      'speaker-low-volume' |
      'speaker-medium-volume' |
      'speaking-head' |
      'speech-balloon' |
      'speedboat' |
      'spider-web' |
      'spider' |
      'spiral-calendar' |
      'spiral-notepad' |
      'spiral-shell' |
      'spoon' |
      'sport-utility-vehicle' |
      'sports-medal' |
      'spouting-whale' |
      'squid' |
      'squinting-face-with-tongue' |
      'stadium' |
      'star-and-crescent' |
      'star-of-david' |
      'star' |
      'station' |
      'statue-of-liberty' |
      'steaming-bowl' |
      'stop-button' |
      'stop-sign' |
      'stopwatch' |
      'straight-ruler' |
      'strawberry' |
      'studio-microphone' |
      'stuffed-flatbread' |
      'sun-behind-cloud' |
      'sun-behind-large-cloud' |
      'sun-behind-rain-cloud' |
      'sun-behind-small-cloud' |
      'sun-with-face' |
      'sun' |
      'sunflower' |
      'sunglasses' |
      'sunrise-over-mountains' |
      'sunrise' |
      'sunset' |
      'sushi' |
      'suspension-railway' |
      'sweat-droplets' |
      'synagogue' |
      'syringe' |
      't-shirt' |
      'taco' |
      'tanabata-tree' |
      'tangerine' |
      'taurus' |
      'taxi' |
      'teacup-without-handle' |
      'tear-off-calendar' |
      'telephone-receiver' |
      'telephone' |
      'telescope' |
      'television' |
      'ten-oclock' |
      'ten-thirty' |
      'tennis' |
      'tent' |
      'thermometer' |
      'thinking-face' |
      'thought-balloon' |
      'three-oclock' |
      'three-thirty' |
      'thumbs-down-dark-skin-tone' |
      'thumbs-down-light-skin-tone' |
      'thumbs-down-medium-dark-skin-tone' |
      'thumbs-down-medium-light-skin-tone' |
      'thumbs-down-medium-skin-tone' |
      'thumbs-down' |
      'thumbs-up-dark-skin-tone' |
      'thumbs-up-light-skin-tone' |
      'thumbs-up-medium-dark-skin-tone' |
      'thumbs-up-medium-light-skin-tone' |
      'thumbs-up-medium-skin-tone' |
      'thumbs-up' |
      'ticket' |
      'tiger-face' |
      'tiger' |
      'timer-clock' |
      'tired-face' |
      'toilet' |
      'tokyo-tower' |
      'tomato' |
      'tongue' |
      'top-arrow' |
      'top-hat' |
      'tornado' |
      'trackball' |
      'tractor' |
      'trade-mark' |
      'train' |
      'tram-car' |
      'tram' |
      'triangular-ruler' |
      'trident-emblem' |
      'trolleybus' |
      'trophy' |
      'tropical-drink' |
      'tropical-fish' |
      'trumpet' |
      'tulip' |
      'tumbler-glass' |
      'turkey' |
      'turtle' |
      'twelve-oclock' |
      'twelve-thirty' |
      'two-hearts' |
      'two-hump-camel' |
      'two-men-holding-hands' |
      'two-oclock' |
      'two-thirty' |
      'two-women-holding-hands' |
      'umbrella-on-ground' |
      'umbrella-with-rain-drops' |
      'umbrella' |
      'unamused-face' |
      'unicorn-face' |
      'unlocked' |
      'up-arrow' |
      'up-down-arrow' |
      'up-left-arrow' |
      'up-right-arrow' |
      'up-text-button' |
      'upside-down-face' |
      'upwards-button' |
      'vertical-traffic-light' |
      'vibration-mode' |
      'victory-hand-dark-skin-tone' |
      'victory-hand-light-skin-tone' |
      'victory-hand-medium-dark-skin-tone' |
      'victory-hand-medium-light-skin-tone' |
      'victory-hand-medium-skin-tone' |
      'victory-hand' |
      'video-camera' |
      'video-game' |
      'videocassette' |
      'violin' |
      'virgo' |
      'volcano' |
      'volleyball' |
      'vs-button' |
      'vulcan-salute-dark-skin-tone' |
      'vulcan-salute-light-skin-tone' |
      'vulcan-salute-medium-dark-skin-tone' |
      'vulcan-salute-medium-light-skin-tone' |
      'vulcan-salute-medium-skin-tone' |
      'vulcan-salute' |
      'waning-crescent-moon' |
      'waning-gibbous-moon' |
      'warning' |
      'wastebasket' |
      'watch' |
      'water-buffalo' |
      'water-closet' |
      'water-wave' |
      'watermelon' |
      'waving-hand-dark-skin-tone' |
      'waving-hand-light-skin-tone' |
      'waving-hand-medium-dark-skin-tone' |
      'waving-hand-medium-light-skin-tone' |
      'waving-hand-medium-skin-tone' |
      'waving-hand' |
      'wavy-dash' |
      'waxing-crescent-moon' |
      'waxing-gibbous-moon' |
      'weary-cat-face' |
      'weary-face' |
      'wedding' |
      'whale' |
      'wheel-of-dharma' |
      'wheelchair-symbol' |
      'white-circle' |
      'white-exclamation-mark' |
      'white-flower' |
      'white-heavy-check-mark' |
      'white-large-square' |
      'white-medium-small-square' |
      'white-medium-square' |
      'white-question-mark' |
      'white-small-square' |
      'white-square-button' |
      'wilted-flower' |
      'wind-chime' |
      'wind-face' |
      'wine-glass' |
      'winking-face-with-tongue' |
      'winking-face' |
      'wolf' |
      'woman-dancing-dark-skin-tone' |
      'woman-dancing-light-skin-tone' |
      'woman-dancing-medium-dark-skin-tone' |
      'woman-dancing-medium-light-skin-tone' |
      'woman-dancing-medium-skin-tone' |
      'woman-dancing' |
      'woman-dark-skin-tone' |
      'woman-light-skin-tone' |
      'woman-medium-dark-skin-tone' |
      'woman-medium-light-skin-tone' |
      'woman-medium-skin-tone' |
      'woman' |
      'womans-boot' |
      'womans-clothes' |
      'womans-hat' |
      'womans-sandal' |
      'womens-room' |
      'world-map' |
      'worried-face' |
      'wrapped-gift' |
      'wrench' |
      'writing-hand-dark-skin-tone' |
      'writing-hand-light-skin-tone' |
      'writing-hand-medium-dark-skin-tone' |
      'writing-hand-medium-light-skin-tone' |
      'writing-hand-medium-skin-tone' |
      'writing-hand' |
      'yellow-heart' |
      'yen-banknote' |
      'yin-yang' |
      'zipper-mouth-face' |
      'zzz';

    type backgroundType = 'circle' | 'rect' | 'button';

    type positionType = 'top' | 'bottom' | 'right' | 'left' |
      'top_right' | 'top_left' | 'bottom_right' | 'bottom_left';

    type backgroundTypeObj = {
      type?: backgroundType;
      color?: string;
      radius?: number;
      borderRadius?: number;
    };

    type badgeTypeObj = {
      value?: number | string;
      fontSize?: string;
      position?: positionType;
      color?: string;
      backgroundColor?: string;
      radius?: number;
    };

    interface IconProps {
      name: iconNames;
      width?: number;
      height?: number;
      color?: string;
      stroke?: number;
      background?: backgroundType | backgroundTypeObj;
      badge?: number | string | badgeTypeObj;
    }

    const Icon: (props: IconProps & SvgProps & AdditionalProps) => ReactNode;

    export { iconNames };
    export default Icon;
}
