declare module 'react-native-ico-emojione-emojis' {
    import { ReactNode } from 'react';
    import { SvgProps } from 'react-native-svg';

    type AdditionalProps = {
      onError?: (error: Error) => void;
      onLoad?: () => void;
      fallback?: ReactNode;
    };

    type iconNames = 'flag-for-czechia' |
      'id-button' |
      'folded-hands-dark-skin-tone' |
      'mans-shoe' |
      'index-pointing-up-medium-skin-tone' |
      'construction-worker-medium-skin-tone' |
      'person-playing-handball-medium-skin-tone' |
      'flag-for-yemen' |
      'last-quarter-moon' |
      'backhand-index-pointing-up-medium-dark-skin-tone' |
      'flexed-biceps-medium-dark-skin-tone' |
      'counterclockwise-arrows-button' |
      'person-bouncing-ball-light-skin-tone' |
      'thumbs-down-medium-skin-tone' |
      'right-anger-bubble' |
      'sneezing-face' |
      'clamp' |
      'sunrise' |
      'globe-showing-asia-australia' |
      'two-hearts' |
      'doughnut' |
      'kissing-face-with-closed-eyes' |
      'pound-banknote' |
      'panda-face' |
      'japanese-not-free-of-charge-button' |
      'battery' |
      'mrs-claus-medium-dark-skin-tone' |
      'ear-of-corn' |
      'middle-finger-medium-skin-tone' |
      'japanese-symbol-for-beginner' |
      'person-getting-massage-light-skin-tone' |
      'flag-for-st-lucia' |
      'spider' |
      'musical-note' |
      'cow' |
      'cheese-wedge' |
      'flag-for-rainbow-flag' |
      'flag-for-nigeria' |
      'person-gesturing-ok-medium-skin-tone' |
      'baby-medium-skin-tone' |
      'droplet' |
      'euro-banknote' |
      'flexed-biceps-dark-skin-tone' |
      'family-woman-woman-boy-boy' |
      'letter-c' |
      'people-wrestling-medium-light-skin-tone' |
      'letter-t' |
      'satellite' |
      'writing-hand-medium-light-skin-tone' |
      '3rd-place-medal' |
      'soon-arrow' |
      'leopard' |
      'thumbs-down-dark-skin-tone' |
      'passport-control' |
      'person-gesturing-no-dark-skin-tone' |
      'left-arrow' |
      'mobile-phone-with-arrow' |
      'man' |
      'flag-for-switzerland' |
      'fire' |
      'ok-hand-medium-light-skin-tone' |
      'person-playing-water-polo-medium-light-skin-tone' |
      'map-of-japan' |
      'flag-for-palestinian-territories' |
      'hand-with-fingers-splayed-dark-skin-tone' |
      'woman-dancing-medium-light-skin-tone' |
      'right-arrow-curving-left' |
      'flag-for-clipperton-island' |
      'flag-for-mauritius' |
      'thumbs-up' |
      'alembic' |
      'dog' |
      'person-frowning-medium-light-skin-tone' |
      'man-in-suit-levitating' |
      'package' |
      'astonished-face' |
      'ring' |
      'money-with-wings' |
      'frowning-face' |
      'calendar' |
      'tram' |
      'face-with-tongue' |
      'aerial-tramway' |
      'handbag' |
      'waving-hand-light-skin-tone' |
      'white-medium-square' |
      'ballot-box-with-ballot' |
      'letter-k' |
      'bow-and-arrow' |
      'ear-dark-skin-tone' |
      'airplane-arrival' |
      'letter-m' |
      'flag-for-guinea-bissau' |
      'flag-for-lebanon' |
      'bomb' |
      'japanese-service-charge-button' |
      'flag-for-eritrea' |
      'baby-bottle' |
      'a-button' |
      'bell' |
      'flag-for-luxembourg' |
      'man-in-tuxedo-dark-skin-tone' |
      'face-blowing-a-kiss' |
      'rosette' |
      'person-golfing' |
      'shallow-pan-of-food' |
      'five-oclock' |
      'kick-scooter' |
      'jack-o-lantern' |
      'flag-for-seychelles' |
      'crying-face' |
      'latin-cross' |
      'glasses' |
      'rainbow' |
      'hot-dog' |
      'shaved-ice' |
      'person-swimming-dark-skin-tone' |
      'desert-island' |
      'person-taking-bath-medium-dark-skin-tone' |
      'nose-dark-skin-tone' |
      'flag-for-svalbard-and-jan-mayen' |
      'triangular-ruler' |
      'input-numbers' |
      'guard' |
      'flag-for-st-barthelemy' |
      'flag-for-american-samoa' |
      'backhand-index-pointing-left-medium-light-skin-tone' |
      'person-biking-dark-skin-tone' |
      'newspaper' |
      'flag-for-hungary' |
      'badminton' |
      'duck' |
      'people-wrestling-medium-dark-skin-tone' |
      'up-text-button' |
      'person-gesturing-no-medium-light-skin-tone' |
      'skull' |
      'pig' |
      'person-playing-water-polo-light-skin-tone' |
      'green-heart' |
      'bride-with-veil' |
      'old-woman-medium-skin-tone' |
      'white-question-mark' |
      'school' |
      'face-with-thermometer' |
      'middle-finger-medium-light-skin-tone' |
      'flag-for-niger' |
      'index-pointing-up-medium-light-skin-tone' |
      'magnifying-glass-tilted-left' |
      'keycap-0' |
      'no-smoking' |
      'raised-hand-medium-light-skin-tone' |
      'old-key' |
      'medium-dark-skin-tone' |
      'double-exclamation-mark' |
      'flag-for-jersey' |
      'pick' |
      'speaker-low-volume' |
      'page-with-curl' |
      'bus-stop' |
      'railway-track' |
      'left-facing-fist-light-skin-tone' |
      'cooked-rice' |
      'detective-light-skin-tone' |
      'call-me-hand' |
      'eye-in-speech-bubble' |
      'japanese-prohibited-button' |
      'guard-dark-skin-tone' |
      'no-entry' |
      'flag-in-hole' |
      'person-walking-light-skin-tone' |
      'ballot-box-with-check' |
      'tumbler-glass' |
      'snowman' |
      'flag-for-kiribati' |
      'motorcycle' |
      'shopping-bags' |
      'flag-for-belize' |
      'keycap-3' |
      'flag-for-sweden' |
      'letter-l' |
      'sun-behind-rain-cloud' |
      'relieved-face' |
      'sun-with-face' |
      'person-running-medium-skin-tone' |
      'ticket' |
      'input-latin-lowercase' |
      'see-no-evil-monkey' |
      'person-frowning-dark-skin-tone' |
      'flag-for-rwanda' |
      'glass-of-milk' |
      'flag-for-maldives' |
      'flag-for-madagascar' |
      'nut-and-bolt' |
      'wrench' |
      'large-blue-diamond' |
      'old-woman-medium-light-skin-tone' |
      'camel' |
      'ant' |
      'face-with-medical-mask' |
      'smiling-face-with-halo' |
      'tropical-drink' |
      'small-orange-diamond' |
      'guard-medium-dark-skin-tone' |
      'person-biking-medium-light-skin-tone' |
      'trophy' |
      'vibration-mode' |
      'flag-for-vietnam' |
      'snowflake' |
      'person-getting-massage' |
      'person-getting-haircut' |
      'mrs-claus-light-skin-tone' |
      'crab' |
      'club-suit' |
      'basketball' |
      'japanese-monthly-amount-button' |
      'hand-with-fingers-splayed-medium-light-skin-tone' |
      'video-camera' |
      'selfie-medium-light-skin-tone' |
      'white-circle' |
      'exclamation-mark' |
      'slightly-smiling-face' |
      'detective-dark-skin-tone' |
      'flag-for-kosovo' |
      'flag-for-martinique' |
      'flag-for-kenya' |
      'crossed-fingers-medium-dark-skin-tone' |
      'department-store' |
      'writing-hand-light-skin-tone' |
      'girl-dark-skin-tone' |
      'flag-for-bahamas' |
      'raised-back-of-hand-dark-skin-tone' |
      'vulcan-salute' |
      'japanese-discount-button' |
      'handshake-medium-light-skin-tone' |
      'b-button' |
      'flag-for-sri-lanka' |
      'vulcan-salute-light-skin-tone' |
      'person-lifting-weights-medium-skin-tone' |
      'waving-hand-medium-skin-tone' |
      'white-large-square' |
      'old-man' |
      'person-frowning' |
      'winking-face' |
      'nerd-face' |
      'people-wrestling-dark-skin-tone' |
      'ng-button' |
      'flag-for-australia' |
      'man-dancing-medium-light-skin-tone' |
      'womans-clothes' |
      'thumbs-down' |
      'pregnant-woman-dark-skin-tone' |
      'prohibited' |
      'houses' |
      'keycap-8' |
      'moai' |
      'slot-machine' |
      'flag-for-guinea' |
      'vertical-traffic-light' |
      'flag-for-uruguay' |
      'watch' |
      'waning-crescent-moon' |
      'input-latin-uppercase' |
      'paintbrush' |
      'oncoming-fist' |
      'sun' |
      'fountain-pen' |
      'police-officer-light-skin-tone' |
      'thumbs-up-medium-skin-tone' |
      'four-leaf-clover' |
      'family-woman-woman-boy' |
      'speech-balloon' |
      'flag-for-comoros' |
      'soccer-ball' |
      'girl' |
      'post-office' |
      'person-wearing-turban-medium-light-skin-tone' |
      'bed' |
      'person-running-medium-dark-skin-tone' |
      'man-dancing-light-skin-tone' |
      'flag-for-black-flag' |
      'volcano' |
      'curry-rice' |
      'flag-for-french-guiana' |
      'ok-hand-medium-skin-tone' |
      'oncoming-fist-medium-skin-tone' |
      'santa-claus-dark-skin-tone' |
      'circled-m' |
      'folded-hands-medium-dark-skin-tone' |
      'japanese-vacancy-button' |
      'white-medium-small-square' |
      'person-surfing-medium-light-skin-tone' |
      'keycap-2' |
      'five-thirty' |
      'control-knobs' |
      'person-tipping-hand' |
      'thumbs-down-medium-dark-skin-tone' |
      'person-juggling-medium-dark-skin-tone' |
      'globe-showing-europe-africa' |
      'star' |
      'butterfly' |
      'busts-in-silhouette' |
      'spiral-calendar' |
      'nail-polish-medium-skin-tone' |
      'meat-on-bone' |
      'flag-for-anguilla' |
      'crossed-fingers-dark-skin-tone' |
      'hand-with-fingers-splayed' |
      'hamster-face' |
      'flag-for-ghana' |
      'medium-skin-tone' |
      'wine-glass' |
      'owl' |
      'baggage-claim' |
      'snowman-without-snow' |
      'boy-medium-skin-tone' |
      'shark' |
      'flag-for-france' |
      'stuffed-flatbread' |
      'balance-scale' |
      'santa-claus-medium-light-skin-tone' |
      'dim-button' |
      'letter-h' |
      'keycap-6' |
      'shrimp' |
      'raised-fist-dark-skin-tone' |
      'backhand-index-pointing-down-medium-dark-skin-tone' |
      'nail-polish' |
      'woman-dancing' |
      'backhand-index-pointing-left-medium-dark-skin-tone' |
      'prince-light-skin-tone' |
      'bell-with-slash' |
      'fast-forward-button' |
      'bread' |
      'person-walking-medium-skin-tone' |
      'flag-for-gambia' |
      'next-track-button' |
      'flag-for-hong-kong-sar-china' |
      'twelve-oclock' |
      'clapping-hands-medium-dark-skin-tone' |
      'kiss' |
      'copyright' |
      'call-me-hand-light-skin-tone' |
      'carrot' |
      'flag-for-northern-mariana-islands' |
      'persevering-face' |
      'ping-pong' |
      'bookmark' |
      'ear-light-skin-tone' |
      'memo' |
      'oncoming-fist-medium-dark-skin-tone' |
      'selfie-medium-skin-tone' |
      'raised-back-of-hand-medium-light-skin-tone' |
      'flag-for-denmark' |
      'person-lifting-weights-dark-skin-tone' |
      'link' |
      'ram' |
      'person-raising-hand-light-skin-tone' |
      'letter-e' |
      'person-taking-bath-medium-light-skin-tone' |
      'flag-for-aruba' |
      'flag-for-romania' |
      'chart-increasing-with-yen' |
      'flag-for-somalia' |
      'computer-mouse' |
      'kitchen-knife' |
      'tangerine' |
      'prince-medium-dark-skin-tone' |
      'japanese-castle' |
      'play-or-pause-button' |
      'flag-for-tajikistan' |
      'sheaf-of-rice' |
      'carousel-horse' |
      'atm-sign' |
      'tear-off-calendar' |
      'barber-pole' |
      'heavy-plus-sign' |
      'pregnant-woman-light-skin-tone' |
      'japanese-congratulations-button' |
      'joystick' |
      'grinning-cat-face' |
      'flag-for-ecuador' |
      'teacup-without-handle' |
      'man-in-tuxedo' |
      'flag-for-cambodia' |
      'princess-medium-skin-tone' |
      'person-shrugging-light-skin-tone' |
      'man-with-chinese-cap-light-skin-tone' |
      'flag-for-vatican-city' |
      'right-facing-fist-medium-skin-tone' |
      'person-playing-water-polo-medium-dark-skin-tone' |
      'prayer-beads' |
      'video-game' |
      'snowboarder' |
      'water-buffalo' |
      'artist-palette' |
      'backhand-index-pointing-up-medium-skin-tone' |
      'monkey' |
      'toilet' |
      'baby-medium-light-skin-tone' |
      'moon-viewing-ceremony' |
      'flag-for-tokelau' |
      'blond-haired-person-medium-skin-tone' |
      'kissing-face' |
      'grinning-cat-face-with-smiling-eyes' |
      'flag-for-ceuta-and-melilla' |
      'potato' |
      'fish-cake-with-swirl' |
      'lollipop' |
      'flag-for-us-outlying-islands' |
      'hole' |
      'flag-for-puerto-rico' |
      'face-savoring-food' |
      'paw-prints' |
      'sun-behind-cloud' |
      'envelope' |
      'police-car-light' |
      'mushroom' |
      'hugging-face' |
      'rabbit' |
      'person-rowing-boat-medium-dark-skin-tone' |
      'cricket-game' |
      'construction-worker-medium-dark-skin-tone' |
      'nail-polish-medium-light-skin-tone' |
      'sparkling-heart' |
      'frowning-face-with-open-mouth' |
      'nose-light-skin-tone' |
      'dragon-face' |
      'flag-for-bhutan' |
      'open-hands-medium-dark-skin-tone' |
      'man-dancing-dark-skin-tone' |
      'santa-claus-medium-dark-skin-tone' |
      'black-nib' |
      'cow-face' |
      'raised-hand-medium-dark-skin-tone' |
      'pear' |
      'flag-for-latvia' |
      'flag-for-crossed-flags' |
      'flag-for-wallis-and-futuna' |
      'backhand-index-pointing-down-medium-skin-tone' |
      'letter-v' |
      'beating-heart' |
      'flag-for-venezuela' |
      'seven-oclock' |
      'cloud-with-lightning' |
      'ten-thirty' |
      'dango' |
      'person-pouting-medium-light-skin-tone' |
      'flag-for-libya' |
      'minibus' |
      'three-oclock' |
      'spoon' |
      'waving-hand-medium-light-skin-tone' |
      'sport-utility-vehicle' |
      'bust-in-silhouette' |
      'purple-heart' |
      'chipmunk' |
      'flag-for-peru' |
      'keycap-asterisk' |
      'umbrella' |
      'honey-pot' |
      'face-screaming-in-fear' |
      'person-gesturing-no-medium-skin-tone' |
      'last-track-button' |
      'prince-medium-light-skin-tone' |
      'closed-mailbox-with-lowered-flag' |
      'backhand-index-pointing-right' |
      'woman-light-skin-tone' |
      'tropical-fish' |
      'worried-face' |
      'bat' |
      'red-heart' |
      'keycap-7' |
      'man-in-tuxedo-light-skin-tone' |
      'clinking-beer-mugs' |
      'person-swimming-medium-light-skin-tone' |
      'horse-face' |
      'person-facepalming-dark-skin-tone' |
      'girl-medium-light-skin-tone' |
      'couple-with-heart' |
      'credit-card' |
      'deer' |
      'horse-racing-medium-dark-skin-tone' |
      'clinking-glasses' |
      'articulated-lorry' |
      'selfie' |
      'water-closet' |
      'flag-for-turkmenistan' |
      'ambulance' |
      'confetti-ball' |
      'lizard' |
      'open-hands-dark-skin-tone' |
      'angry-face-with-horns' |
      'flag-for-cape-verde' |
      'flag-for-saudi-arabia' |
      'flag-for-nepal' |
      'kiss-woman-woman' |
      'person-gesturing-ok-dark-skin-tone' |
      'grimacing-face' |
      'womans-sandal' |
      'flag-for-european-union' |
      'two-men-holding-hands' |
      'dotted-six-pointed-star' |
      'game-die' |
      'beer-mug' |
      'raised-hand-medium-skin-tone' |
      'kiss-mark' |
      'label' |
      'love-letter' |
      'detective-medium-dark-skin-tone' |
      'mouse-face' |
      'person-raising-hand-medium-light-skin-tone' |
      'hushed-face' |
      'smiling-face-with-horns' |
      'raising-hands' |
      'hot-beverage' |
      'baby-angel-dark-skin-tone' |
      'spiral-notepad' |
      'scorpio' |
      'letter-q' |
      'flag-for-guatemala' |
      'victory-hand-light-skin-tone' |
      'woman-dancing-dark-skin-tone' |
      'anger-symbol' |
      'eagle' |
      'speaker-medium-volume' |
      'fox' |
      'fearful-face' |
      'backpack' |
      'unlocked' |
      'face-without-mouth' |
      'flag-for-central-african-republic' |
      'person-playing-handball-light-skin-tone' |
      'backhand-index-pointing-left-dark-skin-tone' |
      'down-right-arrow' |
      'bride-with-veil-medium-skin-tone' |
      'thumbs-up-light-skin-tone' |
      'radio-button' |
      'hand-with-fingers-splayed-light-skin-tone' |
      'cactus' |
      'white-small-square' |
      'classical-building' |
      'flag-for-singapore' |
      'black-square-button' |
      'person-walking' |
      'rocket' |
      'card-index-dividers' |
      'flag-for-bosnia-and-herzegovina' |
      'fountain' |
      'field-hockey' |
      'up-left-arrow' |
      'sushi' |
      'boxing-glove' |
      'selfie-dark-skin-tone' |
      'crossed-fingers' |
      'floppy-disk' |
      'last-quarter-moon-face' |
      'popcorn' |
      'police-car' |
      'file-cabinet' |
      'jeans' |
      'bird' |
      'building-construction' |
      'man-dancing-medium-skin-tone' |
      'flag-for-christmas-island' |
      'santa-claus-light-skin-tone' |
      'flag-for-antigua-and-barbuda' |
      't-shirt' |
      'raising-hands-light-skin-tone' |
      'currency-exchange' |
      'whale' |
      'dragon' |
      'flag-for-congo-brazzaville' |
      'left-arrow-curving-right' |
      'hundred-points' |
      'exclamation-question-mark' |
      'vs-button' |
      'person-juggling-light-skin-tone' |
      'medium-light-skin-tone' |
      'prince' |
      'admission-tickets' |
      'reverse-button' |
      'flag-for-kazakhstan' |
      'flag-for-tuvalu' |
      'flag-for-montserrat' |
      'person-playing-handball' |
      'flag-for-western-sahara' |
      'rolling-on-the-floor-laughing' |
      'p-button' |
      'satellite-antenna' |
      'ok-hand-light-skin-tone' |
      'passenger-ship' |
      'letter-o' |
      'reminder-ribbon' |
      'person-lifting-weights-medium-dark-skin-tone' |
      'flag-for-san-marino' |
      'scissors' |
      'flag-for-armenia' |
      'speak-no-evil-monkey' |
      'backhand-index-pointing-down-light-skin-tone' |
      'kimono' |
      'person-running-medium-light-skin-tone' |
      'balloon' |
      'registered' |
      'elephant' |
      'vulcan-salute-medium-skin-tone' |
      'rose' |
      'shamrock' |
      'speaker-high-volume' |
      'pig-face' |
      'flag-for-estonia' |
      'unamused-face' |
      'construction-worker-medium-light-skin-tone' |
      'cucumber' |
      'flag-scotland' |
      'blond-haired-person-dark-skin-tone' |
      'hear-no-evil-monkey' |
      'flag-for-south-africa' |
      'person-taking-bath-light-skin-tone' |
      'rescue-workers-helmet' |
      'warning' |
      'person-juggling-medium-skin-tone' |
      'construction-worker-dark-skin-tone' |
      'flag-for-french-southern-territories' |
      'six-oclock' |
      'backhand-index-pointing-right-medium-light-skin-tone' |
      'family-man-woman-girl' |
      'bride-with-veil-medium-light-skin-tone' |
      'flag-for-taiwan' |
      'old-woman-light-skin-tone' |
      'libra' |
      'person-bouncing-ball-medium-light-skin-tone' |
      'anchor' |
      'open-hands-medium-light-skin-tone' |
      'raised-fist-medium-light-skin-tone' |
      'police-officer-medium-skin-tone' |
      'up-down-arrow' |
      'three-thirty' |
      'face-with-steam-from-nose' |
      'flag-for-vanuatu' |
      'national-park' |
      'letter-p' |
      'person-getting-massage-medium-light-skin-tone' |
      'princess-dark-skin-tone' |
      'page-facing-up' |
      'new-moon-face' |
      'black-large-square' |
      'beach-with-umbrella' |
      'front-facing-baby-chick' |
      'left-facing-fist-medium-light-skin-tone' |
      'star-of-david' |
      'man-dancing-medium-dark-skin-tone' |
      'waving-hand-medium-dark-skin-tone' |
      'backhand-index-pointing-left-light-skin-tone' |
      'beaming-face-with-smiling-eyes' |
      'flag-for-diego-garcia' |
      'clapping-hands' |
      'o-button' |
      'weary-face' |
      'writing-hand-dark-skin-tone' |
      'heavy-check-mark' |
      'digit-two' |
      'flag-for-canada' |
      'sign-of-the-horns-medium-light-skin-tone' |
      'crystal-ball' |
      'down-left-arrow' |
      'flag-for-st-pierre-and-miquelon' |
      'desert' |
      'flag-for-algeria' |
      'flag-for-austria' |
      'flag-for-trinidad-and-tobago' |
      'kiss-man-man' |
      'flag-for-us-virgin-islands' |
      'cat-face-with-tears-of-joy' |
      'hammer-and-wrench' |
      'person-wearing-turban-dark-skin-tone' |
      'flexed-biceps-medium-light-skin-tone' |
      'end-arrow' |
      'backhand-index-pointing-up-medium-light-skin-tone' |
      'shortcake' |
      'baby-symbol' |
      'airplane' |
      'flag-for-liberia' |
      'people-wrestling-medium-skin-tone' |
      'camping' |
      'running-shoe' |
      'circus-tent' |
      'person-bowing-medium-dark-skin-tone' |
      'flag-for-dominica' |
      'green-book' |
      'man-in-tuxedo-medium-skin-tone' |
      'shield' |
      'motorway' |
      'key' |
      'nail-polish-dark-skin-tone' |
      'squid' |
      'first-quarter-moon' |
      'right-arrow-curving-down' |
      'letter-s' |
      'tomato' |
      'family-man-woman-boy-boy' |
      'blond-haired-person-medium-dark-skin-tone' |
      'guard-medium-skin-tone' |
      'skis' |
      'flag-for-south-georgia-and-south-sandwich-islands' |
      'person-biking-light-skin-tone' |
      'eject-button' |
      'megaphone' |
      'flag-for-congo-kinshasa' |
      'writing-hand' |
      'vulcan-salute-dark-skin-tone' |
      'fast-reverse-button' |
      'index-pointing-up-light-skin-tone' |
      'comet' |
      'heavy-heart-exclamation' |
      'drum' |
      'family-man-man-girl-girl' |
      'stop-sign' |
      'goblin' |
      'flag-for-chequered-flag' |
      'diamond-with-a-dot' |
      'raised-fist-medium-skin-tone' |
      'rhinoceros' |
      'lying-face' |
      'door' |
      'amphora' |
      'double-curly-loop' |
      'umbrella-with-rain-drops' |
      'flag-for-colombia' |
      'letter-g' |
      'flag-for-portugal' |
      'flag-for-djibouti' |
      'cancer' |
      'person-bouncing-ball-dark-skin-tone' |
      'delivery-truck' |
      'snow-capped-mountain' |
      'pouting-cat-face' |
      'sign-of-the-horns-medium-dark-skin-tone' |
      'fallen-leaf' |
      'coffin' |
      'heavy-dollar-sign' |
      'person-rowing-boat-dark-skin-tone' |
      'keycap-9' |
      'keycap-pound' |
      'fleur-de-lis' |
      'flag-for-germany' |
      'crescent-moon' |
      'bottle-with-popping-cork' |
      'open-hands' |
      'high-speed-train' |
      'boy' |
      'digit-nine' |
      'pen' |
      'cookie' |
      'flashlight' |
      'joker' |
      'airplane-departure' |
      'monorail' |
      'shooting-star' |
      'scorpion' |
      'tractor' |
      'japanese-dolls' |
      'customs' |
      'nose-medium-light-skin-tone' |
      'ice-hockey' |
      'horizontal-traffic-light' |
      'violin' |
      'biohazard' |
      'tent' |
      'horse-racing' |
      'umbrella-on-ground' |
      'open-mailbox-with-lowered-flag' |
      'mobile-phone-off' |
      'flag-for-papua-new-guinea' |
      'pig-nose' |
      'oden' |
      'man-medium-skin-tone' |
      'letter-d' |
      'person-getting-haircut-medium-dark-skin-tone' |
      'light-rail' |
      'bride-with-veil-light-skin-tone' |
      'police-officer-dark-skin-tone' |
      'call-me-hand-medium-light-skin-tone' |
      'purse' |
      'bellhop-bell' |
      'blowfish' |
      'flag-for-sudan' |
      'high-voltage' |
      'two-hump-camel' |
      'blue-heart' |
      'grinning-face-with-smiling-eyes' |
      'flag-for-lesotho' |
      'record-button' |
      'flag-for-reunion' |
      'om' |
      'smiling-face-with-smiling-eyes' |
      'menorah' |
      'flag-for-egypt' |
      'shuffle-tracks-button' |
      'person-swimming-medium-skin-tone' |
      '1st-place-medal' |
      'flag-for-gabon' |
      'family-man-man-boy' |
      'top-arrow' |
      'roasted-sweet-potato' |
      'person-pouting' |
      'man-with-chinese-cap' |
      'mountain-cableway' |
      'mrs-claus-medium-light-skin-tone' |
      'flag-for-moldova' |
      'person-gesturing-ok' |
      'spiral-shell' |
      'repeat-button' |
      'loudspeaker' |
      'red-triangle-pointed-down' |
      'dvd' |
      'briefcase' |
      'four-thirty' |
      'flag-for-syria' |
      'funeral-urn' |
      'victory-hand' |
      'person-running' |
      'dizzy-face' |
      'flag-for-bangladesh' |
      'ok-button' |
      'person-facepalming-light-skin-tone' |
      'blond-haired-person-medium-light-skin-tone' |
      'no-mobile-phones' |
      'money-mouth-face' |
      'suspension-railway' |
      'flag-for-serbia' |
      'person-facepalming-medium-light-skin-tone' |
      'aries' |
      'raising-hands-medium-dark-skin-tone' |
      'pencil' |
      'person-running-light-skin-tone' |
      'ten-oclock' |
      'crossed-fingers-light-skin-tone' |
      'motor-scooter' |
      'atom-symbol' |
      'folded-hands-medium-light-skin-tone' |
      'cat-face' |
      'womens-room' |
      'diamond-suit' |
      'flag-for-thailand' |
      'open-mailbox-with-raised-flag' |
      'wheelchair-symbol' |
      'blue-circle' |
      'flag-for-costa-rica' |
      'fried-shrimp' |
      'guard-light-skin-tone' |
      'synagogue' |
      'musical-score' |
      'light-skin-tone' |
      'person-raising-hand-dark-skin-tone' |
      'person-playing-water-polo' |
      'eight-pointed-star' |
      'hatching-chick' |
      'person-frowning-light-skin-tone' |
      'bear-face' |
      'flag-for-argentina' |
      'eyes' |
      'books' |
      'pouting-face' |
      'cocktail-glass' |
      'radio' |
      'flag-for-south-sudan' |
      'prince-medium-skin-tone' |
      'upwards-button' |
      'confounded-face' |
      'victory-hand-medium-skin-tone' |
      'letter-r' |
      'alien-monster' |
      'flag-for-poland' |
      'clapping-hands-dark-skin-tone' |
      'lipstick' |
      'pool-8-ball' |
      'yellow-heart' |
      'money-bag' |
      'top-hat' |
      'flag-for-aland-islands' |
      'pregnant-woman-medium-skin-tone' |
      'flag-for-british-virgin-islands' |
      'couch-and-lamp' |
      'backhand-index-pointing-right-light-skin-tone' |
      'crown' |
      'horse-racing-medium-skin-tone' |
      'person-shrugging-medium-light-skin-tone' |
      'performing-arts' |
      'old-woman-dark-skin-tone' |
      'flag-for-chad' |
      'eggplant' |
      'wheel-of-dharma' |
      'face-with-open-mouth' |
      'baby-medium-dark-skin-tone' |
      'roller-coaster' |
      'sign-of-the-horns' |
      'flag-for-turks-and-caicos-islands' |
      'skier' |
      'horse-racing-light-skin-tone' |
      'aquarius' |
      'helicopter' |
      'white-heavy-check-mark' |
      'yin-yang' |
      'children-crossing' |
      'ear' |
      'person-cartwheeling-medium-skin-tone' |
      'baby-angel-medium-dark-skin-tone' |
      'flag-for-kuwait' |
      'globe-showing-americas' |
      'person-running-dark-skin-tone' |
      'seat' |
      'raised-fist-light-skin-tone' |
      'woman-dark-skin-tone' |
      'thumbs-up-medium-light-skin-tone' |
      'flag-for-united-kingdom' |
      'curly-loop' |
      'flag-for-caribbean-netherlands' |
      'person-walking-medium-dark-skin-tone' |
      'hot-springs' |
      'koala' |
      'downwards-button' |
      'sign-of-the-horns-light-skin-tone' |
      'flag-for-isle-of-man' |
      'heart-decoration' |
      'person-swimming' |
      'boy-dark-skin-tone' |
      'cherries' |
      'steaming-bowl' |
      'left-facing-fist-medium-skin-tone' |
      'pregnant-woman' |
      'flag-for-paraguay' |
      'carp-streamer' |
      'blossom' |
      'flag-for-ukraine' |
      'eight-oclock' |
      'pregnant-woman-medium-light-skin-tone' |
      'on-arrow' |
      'raised-hand' |
      'pineapple' |
      'love-hotel' |
      'skull-and-crossbones' |
      'ghost' |
      'soft-ice-cream' |
      'crossed-fingers-medium-skin-tone' |
      'japanese-application-button' |
      'foggy' |
      'cinema' |
      'railway-car' |
      'flag-for-tanzania' |
      'flag-for-panama' |
      'open-book' |
      'flag-for-israel' |
      'right-facing-fist' |
      'flag-for-marshall-islands' |
      'flag-for-macedonia' |
      'fishing-pole' |
      'desktop-computer' |
      'scroll' |
      'call-me-hand-medium-dark-skin-tone' |
      'handshake-medium-skin-tone' |
      'trade-mark' |
      'flag-for-nicaragua' |
      'tired-face' |
      'flag-for-sao-tome-and-principe' |
      'japanese-open-for-business-button' |
      'flag-for-ascension-island' |
      'shopping-cart' |
      'large-orange-diamond' |
      'outbox-tray' |
      'chicken' |
      'information' |
      'framed-picture' |
      'train' |
      'person-surfing-light-skin-tone' |
      'green-apple' |
      'flag-for-mauritania' |
      'mountain-railway' |
      'person-playing-water-polo-medium-skin-tone' |
      'waving-hand' |
      'flag-for-jordan' |
      'flag-for-croatia' |
      'heavy-division-sign' |
      'poultry-leg' |
      'person-bowing' |
      'index-pointing-up' |
      'raising-hands-medium-skin-tone' |
      'flag-for-uganda' |
      'letter-f' |
      'ear-medium-dark-skin-tone' |
      'family-woman-woman-girl-girl' |
      'guard-medium-light-skin-tone' |
      'cloud' |
      'left-speech-bubble' |
      'flag-for-el-salvador' |
      'man-with-chinese-cap-medium-light-skin-tone' |
      'kissing-cat-face' |
      'police-officer-medium-light-skin-tone' |
      'letter-j' |
      'motor-boat' |
      'tiger-face' |
      'backhand-index-pointing-right-dark-skin-tone' |
      'laptop-computer' |
      'letter-b' |
      'station' |
      'thought-balloon' |
      'orange-book' |
      'flag-for-angola' |
      'milky-way' |
      'person-cartwheeling' |
      'handshake' |
      'person-rowing-boat-medium-skin-tone' |
      'construction-worker' |
      'man-light-skin-tone' |
      'cat' |
      'pound-symbol' |
      'capricorn' |
      'flag-for-faroe-islands' |
      'videocassette' |
      'fireworks' |
      'backhand-index-pointing-right-medium-skin-tone' |
      'dark-skin-tone' |
      'flag-for-st-vincent-and-grenadines' |
      'no-pedestrians' |
      'expressionless-face' |
      'flag-for-micronesia' |
      'left-facing-fist' |
      'small-blue-diamond' |
      'person-pouting-medium-skin-tone' |
      'family-man-woman-girl-boy' |
      'ferris-wheel' |
      'angry-face' |
      'flag-for-turkey' |
      'flag-for-cote-divoire' |
      'old-man-light-skin-tone' |
      'mens-room' |
      'raised-back-of-hand-light-skin-tone' |
      'sign-of-the-horns-medium-skin-tone' |
      'no-one-under-eighteen' |
      'sleepy-face' |
      'microscope' |
      'backhand-index-pointing-down' |
      'no-bicycles' |
      'person-mountain-biking-dark-skin-tone' |
      'person-gesturing-no' |
      'ogre' |
      'letter-z' |
      'gem-stone' |
      'boy-medium-dark-skin-tone' |
      'smirking-face' |
      'person-pouting-light-skin-tone' |
      'person-getting-haircut-dark-skin-tone' |
      'play-button' |
      'heavy-minus-sign' |
      'call-me-hand-medium-skin-tone' |
      'spade-suit' |
      'star-and-crescent' |
      'dashing-away' |
      'letter-u' |
      'person-rowing-boat-light-skin-tone' |
      'trackball' |
      'crying-cat-face' |
      'incoming-envelope' |
      'disappointed-face' |
      'fog' |
      'baby-angel-medium-skin-tone' |
      'derelict-house' |
      'sagittarius' |
      'grinning-squinting-face' |
      'princess-medium-light-skin-tone' |
      'shinto-shrine' |
      'waxing-gibbous-moon' |
      'vulcan-salute-medium-dark-skin-tone' |
      'horse-racing-medium-light-skin-tone' |
      'file-folder' |
      'flag-for-russia' |
      'american-football' |
      'wilted-flower' |
      'call-me-hand-dark-skin-tone' |
      'flushed-face' |
      'monkey-face' |
      'card-index' |
      'person-facepalming-medium-skin-tone' |
      'flag-for-nauru' |
      'nauseated-face' |
      'oncoming-fist-dark-skin-tone' |
      'person-wearing-turban-medium-skin-tone' |
      'girl-medium-dark-skin-tone' |
      'flag-for-morocco' |
      'mouth' |
      'baby-light-skin-tone' |
      'person-playing-water-polo-dark-skin-tone' |
      'letter-y' |
      'flag-for-united-states' |
      'graduation-cap' |
      'family-man-man-girl' |
      'clipboard' |
      'boar' |
      'twelve-thirty' |
      'strawberry' |
      'flag-for-monaco' |
      'folded-hands-medium-skin-tone' |
      'lion-face' |
      'camera-with-flash' |
      'couple-with-heart-man-man' |
      'person-bowing-dark-skin-tone' |
      'old-woman' |
      'herb' |
      'man-with-chinese-cap-dark-skin-tone' |
      'person-bouncing-ball' |
      'baby' |
      'flag-for-mali' |
      'japanese-acceptable-button' |
      'leo' |
      'mountain' |
      'mosque' |
      'flag-for-guyana' |
      'ice-cream' |
      'black-medium-square' |
      'smiling-face-with-sunglasses' |
      'person-rowing-boat-medium-light-skin-tone' |
      'flag-for-canary-islands' |
      'flag-for-mozambique' |
      'flag-for-british-indian-ocean-territory' |
      'convenience-store' |
      'flag-for-iran' |
      'person-gesturing-ok-light-skin-tone' |
      'candle' |
      'input-latin-letters' |
      'winking-face-with-tongue' |
      'handshake-medium-dark-skin-tone' |
      'chart-decreasing' |
      'guitar' |
      'cloud-with-lightning-and-rain' |
      'raising-hands-medium-light-skin-tone' |
      'person-tipping-hand-light-skin-tone' |
      'woman-medium-light-skin-tone' |
      'wind-chime' |
      'eight-spoked-asterisk' |
      'full-moon-face' |
      'red-apple' |
      'growing-heart' |
      'flag-for-dominican-republic' |
      'litter-in-bin-sign' |
      'unicorn-face' |
      'rice-cracker' |
      'black-medium-small-square' |
      'sun-behind-small-cloud' |
      'green-salad' |
      'volleyball' |
      'necktie' |
      'straight-ruler' |
      'tongue' |
      'person-rowing-boat' |
      'octopus' |
      'envelope-with-arrow' |
      'cool-button' |
      'fast-up-button' |
      'bug' |
      'spider-web' |
      'zipper-mouth-face' |
      'sad-but-relieved-face' |
      'nose-medium-dark-skin-tone' |
      'raised-back-of-hand-medium-dark-skin-tone' |
      'selfie-light-skin-tone' |
      'grinning-face-with-sweat' |
      'hammer' |
      'stadium' |
      'princess-medium-dark-skin-tone' |
      'avocado' |
      'rat' |
      'timer-clock' |
      'repeat-single-button' |
      'left-facing-fist-medium-dark-skin-tone' |
      'sign-of-the-horns-dark-skin-tone' |
      'lady-beetle' |
      'detective' |
      'martial-arts-uniform' |
      'gorilla' |
      'open-file-folder' |
      'flag-for-laos' |
      'flag-for-italy' |
      'hourglass-not-done' |
      'turtle' |
      'grinning-face' |
      'flower-playing-cards' |
      'baby-chick' |
      'bride-with-veil-medium-dark-skin-tone' |
      'flag-for-cocos-islands' |
      'antenna-bars' |
      'person-lifting-weights-light-skin-tone' |
      'person-frowning-medium-dark-skin-tone' |
      'womans-boot' |
      'taurus' |
      'person-cartwheeling-medium-dark-skin-tone' |
      'hot-pepper' |
      'flag-for-st-helena' |
      'ice-skate' |
      'flag-for-cayman-islands' |
      'flexed-biceps' |
      'clapping-hands-medium-skin-tone' |
      'spouting-whale' |
      'digit-zero' |
      'two-women-holding-hands' |
      'church' |
      'night-with-stars' |
      'no-littering' |
      'flexed-biceps-light-skin-tone' |
      'old-man-medium-dark-skin-tone' |
      'small-airplane' |
      'man-medium-dark-skin-tone' |
      'two-thirty' |
      'trumpet' |
      'man-dark-skin-tone' |
      'person-wearing-turban-medium-dark-skin-tone' |
      'keycap-10' |
      'digit-four' |
      'full-moon' |
      'flexed-biceps-medium-skin-tone' |
      'poodle' |
      'mrs-claus-dark-skin-tone' |
      'bank' |
      'flag-for-china' |
      'flag-for-cyprus' |
      '2nd-place-medal' |
      'snake' |
      'person-bowing-medium-light-skin-tone' |
      'fire-engine' |
      'right-facing-fist-medium-dark-skin-tone' |
      'girl-medium-skin-tone' |
      'nail-polish-medium-dark-skin-tone' |
      'water-wave' |
      'mount-fuji' |
      'flag-for-spain' |
      'white-flower' |
      'four-oclock' |
      'flag-for-chile' |
      'round-pushpin' |
      'watermelon' |
      'middle-finger' |
      'heart-with-arrow' |
      'flag-england' |
      'ok-hand-medium-dark-skin-tone' |
      'mrs-claus-medium-skin-tone' |
      'sparkles' |
      'rooster' |
      'input-symbols' |
      'cigarette' |
      'house-with-garden' |
      'oncoming-fist-light-skin-tone' |
      'person-walking-medium-light-skin-tone' |
      'fork-and-knife' |
      'backhand-index-pointing-up' |
      'oncoming-taxi' |
      'letter-x' |
      'printer' |
      'person-gesturing-no-medium-dark-skin-tone' |
      'tokyo-tower' |
      'red-circle' |
      'flag-for-botswana' |
      'film-projector' |
      'locked-with-key' |
      'hotel' |
      'flag-for-grenada' |
      'writing-hand-medium-dark-skin-tone' |
      'sun-behind-large-cloud' |
      'smiling-cat-face-with-heart-eyes' |
      'running-shirt' |
      'hammer-and-pick' |
      'person-cartwheeling-dark-skin-tone' |
      'person-facepalming-medium-dark-skin-tone' |
      'turkey' |
      'raised-hand-dark-skin-tone' |
      'baguette-bread' |
      'hibiscus' |
      'flag-for-barbados' |
      'person-pouting-dark-skin-tone' |
      'person-cartwheeling-medium-light-skin-tone' |
      'wrapped-gift' |
      'broken-heart' |
      'horse' |
      'flag-for-senegal' |
      'ophiuchus' |
      'ear-medium-light-skin-tone' |
      'ox' |
      'pot-of-food' |
      'eleven-oclock' |
      'telephone' |
      'face-with-head-bandage' |
      'person-getting-haircut-medium-skin-tone' |
      'place-of-worship' |
      'wavy-dash' |
      'person-biking-medium-dark-skin-tone' |
      'backhand-index-pointing-down-medium-light-skin-tone' |
      'sports-medal' |
      'metro' |
      'tiger' |
      'oncoming-fist-medium-light-skin-tone' |
      'headphone' |
      'person-lifting-weights' |
      'person-swimming-medium-dark-skin-tone' |
      'chestnut' |
      'family' |
      'maple-leaf' |
      'raised-back-of-hand-medium-skin-tone' |
      'flag-for-benin' |
      'kissing-face-with-smiling-eyes' |
      'pensive-face' |
      'nail-polish-light-skin-tone' |
      'person-bowing-medium-skin-tone' |
      'statue-of-liberty' |
      'girl-light-skin-tone' |
      'flag-for-guadeloupe' |
      'flag-for-malta' |
      'television' |
      'flag-for-swaziland' |
      'sparkler' |
      'non-potable-water' |
      'computer-disk' |
      'black-heart' |
      'nine-thirty' |
      'notebook' |
      'first-quarter-moon-face' |
      'person-taking-bath' |
      'selfie-medium-dark-skin-tone' |
      'lemon' |
      'family-woman-woman-girl-boy' |
      'cloud-with-rain' |
      'person-bouncing-ball-medium-skin-tone' |
      'person-tipping-hand-medium-light-skin-tone' |
      'restroom' |
      'man-with-chinese-cap-medium-dark-skin-tone' |
      'police-officer' |
      'zzz' |
      'right-facing-fist-medium-light-skin-tone' |
      'rabbit-face' |
      'right-facing-fist-dark-skin-tone' |
      'bus' |
      'person-bowing-light-skin-tone' |
      'taco' |
      'flag-for-togo' |
      'dove' |
      'baby-angel' |
      'flag-for-curacao' |
      'light-bulb' |
      'person-juggling' |
      'smiling-face-with-heart-eyes' |
      'person-getting-massage-medium-skin-tone' |
      'black-small-square' |
      'notebook-with-decorative-cover' |
      'sunset' |
      'waning-gibbous-moon' |
      'man-dancing' |
      'thumbs-up-medium-dark-skin-tone' |
      'person-biking' |
      'baby-angel-medium-light-skin-tone' |
      'croissant' |
      'crossed-fingers-medium-light-skin-tone' |
      'closed-book' |
      'person-mountain-biking-medium-light-skin-tone' |
      'left-luggage' |
      'glowing-star' |
      'bento-box' |
      'man-medium-light-skin-tone' |
      'flag-for-white-flag' |
      'person-wearing-turban-light-skin-tone' |
      'flag-for-mongolia' |
      'baseball' |
      'raising-hands-dark-skin-tone' |
      'bridge-at-night' |
      'flag-for-gibraltar' |
      'muted-speaker' |
      'open-hands-light-skin-tone' |
      'flag-for-samoa' |
      'yen-banknote' |
      'middle-finger-light-skin-tone' |
      'person-in-bed' |
      'dolphin' |
      'party-popper' |
      'flag-for-tonga' |
      'flag-for-indonesia' |
      'crayon' |
      'peanuts' |
      'japanese-secret-button' |
      'cherry-blossom' |
      'letter-i' |
      'level-slider' |
      'grinning-face-with-big-eyes' |
      'digit-six' |
      'right-facing-fist-light-skin-tone' |
      'flag-for-oman' |
      'raised-fist-medium-dark-skin-tone' |
      'ok-hand' |
      'cl-button' |
      'people-with-bunny-ears' |
      'family-woman-woman-girl' |
      'ferry' |
      'taxi' |
      'fish' |
      'kaaba' |
      'flag-for-ethiopia' |
      'mahjong-red-dragon' |
      'flag-for-philippines' |
      'person-tipping-hand-medium-skin-tone' |
      'weary-cat-face' |
      'digit-seven' |
      'flag-for-heard-and-mcdonald-islands' |
      'paperclip' |
      'victory-hand-dark-skin-tone' |
      'sparkle' |
      'speedboat' |
      'studio-microphone' |
      'flag-for-st-kitts-and-nevis' |
      'flag-for-montenegro' |
      'mouse' |
      'backhand-index-pointing-right-medium-dark-skin-tone' |
      'gemini' |
      'person-getting-haircut-light-skin-tone' |
      'sos-button' |
      'person-gesturing-ok-medium-light-skin-tone' |
      'flag-for-honduras' |
      'french-fries' |
      'woman-medium-skin-tone' |
      'japanese-free-of-charge-button' |
      'seven-thirty' |
      'person-getting-haircut-medium-light-skin-tone' |
      'person-getting-massage-medium-dark-skin-tone' |
      'pushpin' |
      'pistol' |
      'flag-for-cameroon' |
      'flag-for-triangular-flag' |
      'telephone-receiver' |
      'dollar-banknote' |
      'bar-chart' |
      'letter-w' |
      'chocolate-bar' |
      'rugby-football' |
      'flag-for-cook-islands' |
      'closed-mailbox-with-raised-flag' |
      'flag-for-pitcairn-islands' |
      'hand-with-fingers-splayed-medium-dark-skin-tone' |
      'old-man-medium-light-skin-tone' |
      'asterisk' |
      'waxing-crescent-moon' |
      'family-man-man-boy-boy' |
      'flag-for-burkina-faso' |
      'flag-for-namibia' |
      'movie-camera' |
      'prince-dark-skin-tone' |
      'person-wearing-turban' |
      'fork-and-knife-with-plate' |
      'part-alternation-mark' |
      'digit-five' |
      'black-circle' |
      'person-facepalming' |
      'snail' |
      'stop-button' |
      'backhand-index-pointing-up-dark-skin-tone' |
      'flag-for-uzbekistan' |
      'pizza' |
      'bride-with-veil-dark-skin-tone' |
      'person-gesturing-ok-medium-dark-skin-tone' |
      'kiwi-fruit' |
      'tram-car' |
      'flag-for-greenland' |
      'blond-haired-person-light-skin-tone' |
      'clockwise-vertical-arrows' |
      'recycling-symbol' |
      'right-arrow-curving-up' |
      'flag-for-afghanistan' |
      'fast-down-button' |
      'woman-dancing-light-skin-tone' |
      'person-cartwheeling-light-skin-tone' |
      'princess' |
      'thumbs-down-light-skin-tone' |
      'neutral-face' |
      'digit-three' |
      'flag-for-zambia' |
      'flag-for-andorra' |
      'red-paper-lantern' |
      'thermometer' |
      'person-frowning-medium-skin-tone' |
      'spaghetti' |
      'woman' |
      'camera' |
      'index-pointing-up-medium-dark-skin-tone' |
      'heart-with-ribbon' |
      'new-button' |
      'flag-for-india' |
      'flag-for-netherlands' |
      'old-man-medium-skin-tone' |
      'vulcan-salute-medium-light-skin-tone' |
      'folded-hands-light-skin-tone' |
      'flag-for-malaysia' |
      'santa-claus-medium-skin-tone' |
      'ear-medium-skin-tone' |
      'middle-finger-medium-dark-skin-tone' |
      'person-playing-handball-dark-skin-tone' |
      'people-wrestling-light-skin-tone' |
      'flag-for-brunei' |
      'dagger' |
      'fax-machine' |
      'name-badge' |
      'banana' |
      'speaking-head' |
      'digit-eight' |
      'tennis' |
      'one-oclock' |
      'woman-dancing-medium-dark-skin-tone' |
      'flag-for-sierra-leone' |
      'blond-haired-person' |
      'person-lifting-weights-medium-light-skin-tone' |
      'flag-for-burundi' |
      'person-tipping-hand-dark-skin-tone' |
      'sunglasses' |
      'flag-for-slovakia' |
      'honeybee' |
      'custard' |
      'dog-face' |
      'locked' |
      'man-in-tuxedo-medium-dark-skin-tone' |
      'bicycle' |
      'optical-disk' |
      'flag-for-myanmar' |
      'peach' |
      'bouquet' |
      'man-in-tuxedo-medium-light-skin-tone' |
      'flag-for-bermuda' |
      'flag-for-georgia' |
      'japanese-reserved-button' |
      'wind-face' |
      'locomotive' |
      'flag-for-qatar' |
      'flag-for-norfolk-island' |
      'person-shrugging-dark-skin-tone' |
      'nine-oclock' |
      'trolleybus' |
      'crocodile' |
      'old-man-dark-skin-tone' |
      'police-officer-medium-dark-skin-tone' |
      'bowling' |
      'oncoming-automobile' |
      'chart-increasing' |
      'flag-for-equatorial-guinea' |
      'japanese-bargain-button' |
      'couple-with-heart-woman-woman' |
      'horse-racing-dark-skin-tone' |
      'oncoming-police-car' |
      'family-man-man-girl-boy' |
      'wolf' |
      'left-facing-fist-dark-skin-tone' |
      'right-arrow' |
      'revolving-hearts' |
      'eleven-thirty' |
      'card-file-box' |
      'flag-for-suriname' |
      'person-taking-bath-dark-skin-tone' |
      'house' |
      'one-thirty' |
      'digit-one' |
      'construction' |
      'flag-for-cuba' |
      'birthday-cake' |
      'microphone' |
      'flag-for-brazil' |
      'canoe' |
      'family-man-woman-girl-girl' |
      'anxious-face-with-sweat' |
      'hourglass-done' |
      'cooking' |
      'boy-medium-light-skin-tone' |
      'flag-for-falkland-islands' |
      'flag-for-macau-sar-china' |
      'pile-of-poo' |
      'flag-for-tristan-da-cunha' |
      'pine-decoration' |
      'flag-for-solomon-islands' |
      'baby-dark-skin-tone' |
      'hand-with-fingers-splayed-medium-skin-tone' |
      'saxophone' |
      'downcast-face-with-sweat' |
      'flag-for-palau' |
      'crossed-swords' |
      'backhand-index-pointing-down-dark-skin-tone' |
      'santa-claus' |
      'candy' |
      'syringe' |
      'backhand-index-pointing-left-medium-skin-tone' |
      'clapping-hands-medium-light-skin-tone' |
      'postbox' |
      'electric-plug' |
      'castle' |
      'person-biking-medium-skin-tone' |
      'sleeping-face' |
      'peace-symbol' |
      'person-mountain-biking-light-skin-tone' |
      'flag-for-kyrgyzstan' |
      'mobile-phone' |
      'raised-fist' |
      'folded-hands' |
      'factory' |
      'pregnant-woman-medium-dark-skin-tone' |
      'oncoming-bus' |
      'construction-worker-light-skin-tone' |
      'cyclone' |
      'person-gesturing-no-light-skin-tone' |
      'radioactive' |
      'person-surfing' |
      'person-pouting-medium-dark-skin-tone' |
      'person-raising-hand-medium-skin-tone' |
      'robot-face' |
      'back-arrow' |
      'ledger' |
      'sake' |
      'japanese-post-office' |
      'ewe' |
      'loudly-crying-face' |
      'raised-back-of-hand' |
      'virgo' |
      'middle-finger-dark-skin-tone' |
      'white-exclamation-mark' |
      'stopwatch' |
      'hamburger' |
      'locked-with-pen' |
      'raised-hand-light-skin-tone' |
      'tornado' |
      'potable-water' |
      'flag-for-mayotte' |
      'trident-emblem' |
      'nose' |
      'japanese-here-button' |
      'flag-for-iraq' |
      'boy-light-skin-tone' |
      'nose-medium-skin-tone' |
      'person-swimming-light-skin-tone' |
      'automobile' |
      'person-mountain-biking-medium-dark-skin-tone' |
      'flag-for-timor-leste' |
      'flag-for-malawi' |
      'pancakes' |
      'heart-suit' |
      'flag-for-greece' |
      'thumbs-down-medium-light-skin-tone' |
      'closed-umbrella' |
      'flag-for-guernsey' |
      'confused-face' |
      'flag-for-niue' |
      'person-surfing-medium-skin-tone' |
      'linked-paperclips' |
      'tulip' |
      'flag-for-slovenia' |
      'clutch-bag' |
      'rolled-up-newspaper' |
      'flag-for-mexico' |
      'six-thirty' |
      'face-with-tears-of-joy' |
      'footprints' |
      'flag-for-bolivia' |
      'person-shrugging-medium-dark-skin-tone' |
      'flag-for-tunisia' |
      'up-arrow' |
      'people-wrestling' |
      'flag-for-guam' |
      'waving-hand-dark-skin-tone' |
      'eight-thirty' |
      'japanese-passing-grade-button' |
      'goal-net' |
      'oil-drum' |
      'handshake-dark-skin-tone' |
      'cowboy-hat-face' |
      'flag-for-bahrain' |
      'cross-mark-button' |
      'flag-for-jamaica' |
      'drooling-face' |
      'burrito' |
      'ribbon' |
      'cloud-with-snow' |
      'sunrise-over-mountains' |
      'man-and-woman-holding-hands' |
      'keycap-4' |
      'wastebasket' |
      'old-woman-medium-dark-skin-tone' |
      'cityscape-at-dusk' |
      'princess-light-skin-tone' |
      'flag-for-albania' |
      'goat' |
      'red-triangle-pointed-up' |
      'flag-for-iceland' |
      'squinting-face-with-tongue' |
      'person-fencing' |
      'person-raising-hand' |
      'blue-book' |
      'woman-medium-dark-skin-tone' |
      'writing-hand-medium-skin-tone' |
      'two-oclock' |
      'open-hands-medium-skin-tone' |
      'flag-for-pakistan' |
      'clapping-hands-light-skin-tone' |
      'thumbs-up-dark-skin-tone' |
      'musical-notes' |
      'flag-for-zimbabwe' |
      'flag-for-bulgaria' |
      'evergreen-tree' |
      'person-juggling-medium-light-skin-tone' |
      'bathtub' |
      'flag-for-north-korea' |
      'collision' |
      'letter-a' |
      'slightly-frowning-face' |
      'new-moon' |
      'down-arrow' |
      'orthodox-cross' |
      'man-with-chinese-cap-medium-skin-tone' |
      'sweat-droplets' |
      'seedling' |
      'cat-face-with-wry-smile' |
      'person-juggling-dark-skin-tone' |
      'direct-hit' |
      'deciduous-tree' |
      'up-right-arrow' |
      'thinking-face' |
      'fuel-pump' |
      'film-frames' |
      'mantelpiece-clock' |
      'flag-for-lithuania' |
      'person-bouncing-ball-medium-dark-skin-tone' |
      'index-pointing-up-dark-skin-tone' |
      'detective-medium-light-skin-tone' |
      'woman-dancing-medium-skin-tone' |
      'military-medal' |
      'free-button' |
      'egg' |
      'person-raising-hand-medium-dark-skin-tone' |
      'person-surfing-medium-dark-skin-tone' |
      'penguin' |
      'ship' |
      'eye' |
      'heavy-large-circle' |
      'keycap-5' |
      'leaf-fluttering-in-wind' |
      'face-with-rolling-eyes' |
      'bikini' |
      'office-building' |
      'person-taking-bath-medium-skin-tone' |
      'inbox-tray' |
      'flag-for-azerbaijan' |
      'bacon' |
      'clown-face' |
      'keyboard' |
      'flag-for-haiti' |
      'flag-for-french-polynesia' |
      'alarm-clock' |
      'pisces' |
      'flag-for-bouvet-island' |
      'dress' |
      'flag-for-belgium' |
      'detective-medium-skin-tone' |
      'dizzy' |
      'flag-for-liechtenstein' |
      'wedding' |
      'letter-n' |
      'frog-face' |
      'flag-for-japan' |
      'pause-button' |
      'flag-for-finland' |
      'person-getting-massage-dark-skin-tone' |
      'bright-button' |
      'person-tipping-hand-medium-dark-skin-tone' |
      'cross-mark' |
      'person-playing-handball-medium-dark-skin-tone' |
      'gear' |
      'tanabata-tree' |
      'magnifying-glass-tilted-right' |
      'sailboat' |
      'christmas-tree' |
      'person-mountain-biking' |
      'left-right-arrow' |
      'sunflower' |
      'bookmark-tabs' |
      'flag-for-st-martin' |
      'pill' |
      'womans-hat' |
      'flag-for-antarctica' |
      'alien' |
      'flag-for-new-caledonia' |
      'bullet-train' |
      'person-playing-handball-medium-light-skin-tone' |
      'high-heeled-shoe' |
      'clapper-board' |
      'flag-for-norway' |
      'backhand-index-pointing-left' |
      'person-shrugging-medium-skin-tone' |
      'question-mark' |
      'victory-hand-medium-dark-skin-tone' |
      'ok-hand-dark-skin-tone' |
      'postal-horn' |
      'palm-tree' |
      'upside-down-face' |
      'person-mountain-biking-medium-skin-tone' |
      'pager' |
      'cityscape' |
      'person-walking-dark-skin-tone' |
      'flag-for-belarus' |
      'flag-for-south-korea' |
      'hospital' |
      'smiling-face' |
      'racing-car' |
      'grapes' |
      'world-map' |
      'person-surfing-dark-skin-tone' |
      'rice-ball' |
      'flag-for-ireland' |
      'flag-for-sint-maarten' |
      'chains' |
      'ab-button' |
      'handshake-light-skin-tone' |
      'globe-with-meridians' |
      'flag-for-fiji' |
      'baby-angel-light-skin-tone' |
      'musical-keyboard' |
      'mrs-claus' |
      'backhand-index-pointing-up-light-skin-tone' |
      'flag-for-united-arab-emirates' |
      'keycap-1' |
      'japanese-no-vacancy-button' |
      'flag-for-new-zealand' |
      'anguished-face' |
      'person-shrugging' |
      'melon' |
      'shower' |
      'telescope' |
      'victory-hand-medium-light-skin-tone' |
      'white-square-button';

    type iconColors = '#000000' |
      '#002d62' |
      '#003478' |
      '#005bbf' |
      '#006129' |
      '#0065BD' |
      '#006b00' |
      '#006ec7' |
      '#00713d' |
      '#007168' |
      '#0071b8' |
      '#0071bc' |
      '#007dd4' |
      '#0081c6' |
      '#008db3' |
      '#0091c8' |
      '#00a3d6' |
      '#00a6de' |
      '#00afca' |
      '#00b9f1' |
      '#00c0cf' |
      '#00f' |
      '#01579b' |
      '#034ea2' |
      '#055672' |
      '#076170' |
      '#095972' |
      '#0a84a5' |
      '#0d0d0d' |
      '#0dccd1' |
      '#106995' |
      '#121314' |
      '#13618d' |
      '#144e73' |
      '#161616' |
      '#1778bd' |
      '#1799f8' |
      '#181919' |
      '#181f27' |
      '#18637a' |
      '#1a86b1' |
      '#1b81b6' |
      '#1d8299' |
      '#1e1e1e' |
      '#1e5aa6' |
      '#201b18' |
      '#2090bc' |
      '#212326' |
      '#212528' |
      '#21adf1' |
      '#222526' |
      '#224863' |
      '#22648c' |
      '#231f20' |
      '#242a33' |
      '#24bac5' |
      '#252728' |
      '#256382' |
      '#258399' |
      '#262626' |
      '#275fd9' |
      '#286699' |
      '#2872a0' |
      '#287700' |
      '#288549' |
      '#29251c' |
      '#293030' |
      '#296d8f' |
      '#297b9d' |
      '#298959' |
      '#29abe2' |
      '#29b6f6' |
      '#2a5f9e' |
      '#2b2118' |
      '#2b2925' |
      '#2b2b2b' |
      '#2b4666' |
      '#2b95bf' |
      '#2ba5d6' |
      '#2c3033' |
      '#2caece' |
      '#2e6c93' |
      '#302424' |
      '#302822' |
      '#308776' |
      '#3283ab' |
      '#333' |
      '#334037' |
      '#3383c4' |
      '#3390ff' |
      '#343434' |
      '#347aa5' |
      '#363b3d' |
      '#363b40' |
      '#36a7c1' |
      '#373e42' |
      '#383b3d' |
      '#383f42' |
      '#384044' |
      '#38bfd6' |
      '#3a7dce' |
      '#3a81ad' |
      '#3b302a' |
      '#3b3226' |
      '#3b946f' |
      '#3b9ac9' |
      '#3baacf' |
      '#3d2905' |
      '#3d4347' |
      '#3dd0e0' |
      '#3e4347' |
      '#3f2e29' |
      '#3f3261' |
      '#3f3438' |
      '#3f4237' |
      '#3f4f44' |
      '#4187b7' |
      '#423223' |
      '#42464c' |
      '#425e21' |
      '#428bc1' |
      '#42ade2' |
      '#44618b' |
      '#449636' |
      '#454749' |
      '#45cbea' |
      '#464d51' |
      '#46732f' |
      '#467591' |
      '#468bc4' |
      '#47352d' |
      '#474d51' |
      '#475152' |
      '#47b892' |
      '#484a4c' |
      '#493816' |
      '#493b30' |
      '#494949' |
      '#49c3f2' |
      '#4a352a' |
      '#4a4e51' |
      '#4aa9ff' |
      '#4b4d4f' |
      '#4b53a2' |
      '#4b662b' |
      '#4b7ea3' |
      '#4bd37b' |
      '#4c3526' |
      '#4c3f2e' |
      '#4c5256' |
      '#4c5359' |
      '#4c86c7' |
      '#4d4d4d' |
      '#4d4f59' |
      '#4d5357' |
      '#4e5c66' |
      '#4e6b20' |
      '#4f585b' |
      '#4f5b60' |
      '#4f682e' |
      '#4fa1d9' |
      '#4fc7e8' |
      '#4fd1d9' |
      '#50ffdd' |
      '#51575b' |
      '#51575c' |
      '#523420' |
      '#523b32' |
      '#52575b' |
      '#52595e' |
      '#52c18e' |
      '#52e8b6' |
      '#534741' |
      '#53585b' |
      '#538aa5' |
      '#545b60' |
      '#545b61' |
      '#547725' |
      '#555b61' |
      '#555c60' |
      '#555e63' |
      '#55646d' |
      '#557176' |
      '#558730' |
      '#574137' |
      '#575b5e' |
      '#57a1ce' |
      '#592f5d' |
      '#594640' |
      '#595959' |
      '#596066' |
      '#5995c1' |
      '#59ffba' |
      '#5a666b' |
      '#5a6a6d' |
      '#5b0617' |
      '#5b4c52' |
      '#5b636b' |
      '#5b7f32' |
      '#5b7f38' |
      '#5b97b1' |
      '#5c3f34' |
      '#5c4533' |
      '#5c6368' |
      '#5c6d6d' |
      '#5c750a' |
      '#5d6d74' |
      '#5df6ff' |
      '#5e4433' |
      '#5f5cff' |
      '#5f606c' |
      '#5f6262' |
      '#5f6566' |
      '#60452b' |
      '#60aa00' |
      '#60d4e0' |
      '#616161' |
      '#616466' |
      '#61c2ff' |
      '#6235a8' |
      '#62696d' |
      '#626a6d' |
      '#62727a' |
      '#627a82' |
      '#628441' |
      '#628c2c' |
      '#62bbc7' |
      '#62fbf6' |
      '#633f2c' |
      '#63686b' |
      '#636a6b' |
      '#636c72' |
      '#63a1ba' |
      '#63b6e6' |
      '#646464' |
      '#646669' |
      '#647a87' |
      '#64892f' |
      '#65562d' |
      '#656263' |
      '#656d72' |
      '#65b1ef' |
      '#663030' |
      '#664e27' |
      '#666' |
      '#666c70' |
      '#66b0dd' |
      '#66c2ff' |
      '#66caf2' |
      '#676e72' |
      '#68472c' |
      '#68584d' |
      '#686b6d' |
      '#68963b' |
      '#695b5b' |
      '#696a6b' |
      '#697277' |
      '#69727a' |
      '#69787c' |
      '#699635' |
      '#6a4c2d' |
      '#6aced8' |
      '#6adbc6' |
      '#6b3838' |
      '#6b6b6d' |
      '#6b7278' |
      '#6b767c' |
      '#6b7b7f' |
      '#6baaa7' |
      '#6c368e' |
      '#6c3c78' |
      '#6c732d' |
      '#6c767a' |
      '#6c9925' |
      '#6ceda9' |
      '#6d4934' |
      '#6d533e' |
      '#6d5650' |
      '#6d7275' |
      '#6dd1de' |
      '#6dd337' |
      '#6ea03f' |
      '#6f2833' |
      '#6f43a3' |
      '#6f6f6d' |
      '#6f7980' |
      '#705041' |
      '#71a03a' |
      '#71ad3e' |
      '#724e41' |
      '#725944' |
      '#726256' |
      '#728084' |
      '#728389' |
      '#733449' |
      '#73493f' |
      '#734c31' |
      '#7350ab' |
      '#73deff' |
      '#748a93' |
      '#74948f' |
      '#74e063' |
      '#754e27' |
      '#75676d' |
      '#75a843' |
      '#75b7ea' |
      '#75d6ff' |
      '#76807f' |
      '#769e2a' |
      '#76aa3f' |
      '#77623c' |
      '#778389' |
      '#77994f' |
      '#77a836' |
      '#785440' |
      '#785aa0' |
      '#788287' |
      '#7924a6' |
      '#79c600' |
      '#79d3f7' |
      '#7a2d77' |
      '#7a495a' |
      '#7a5136' |
      '#7a8084' |
      '#7a8891' |
      '#7b853d' |
      '#7bb246' |
      '#7c8d93' |
      '#7ca7bf' |
      '#7cb545' |
      '#7d3d15' |
      '#7d5442' |
      '#7d5847' |
      '#7d593e' |
      '#7d644b' |
      '#7d888e' |
      '#7d8993' |
      '#7d8b91' |
      '#7df0ff' |
      '#7e44bf' |
      '#7e8484' |
      '#7e93a4' |
      '#7ed16d' |
      '#7f5629' |
      '#7f5f52' |
      '#7f8285' |
      '#7fb539' |
      '#7fc6cc' |
      '#802000' |
      '#803c3c' |
      '#804458' |
      '#804c26' |
      '#805b4c' |
      '#805c44' |
      '#805f47' |
      '#808f96' |
      '#819096' |
      '#824000' |
      '#826046' |
      '#827717' |
      '#8387f7' |
      '#838e96' |
      '#839391' |
      '#83b533' |
      '#83b730' |
      '#83bf4f' |
      '#843dc9' |
      '#846144' |
      '#847266' |
      '#84b234' |
      '#84e060' |
      '#85340a' |
      '#856daa' |
      '#85e845' |
      '#860d16' |
      '#86d0bf' |
      '#870014' |
      '#870f00' |
      '#871212' |
      '#879191' |
      '#87989b' |
      '#881a0e' |
      '#896349' |
      '#89664c' |
      '#898a90' |
      '#89967a' |
      '#89969b' |
      '#8a6859' |
      '#8a8e91' |
      '#8a9396' |
      '#8a94a0' |
      '#8a959b' |
      '#8ad8ff' |
      '#8b979e' |
      '#8b9fa5' |
      '#8bce4a' |
      '#8c13d4' |
      '#8c5b3e' |
      '#8c8a8c' |
      '#8ca8c2' |
      '#8cc63e' |
      '#8cddea' |
      '#8d9998' |
      '#8d9ba3' |
      '#8e6244' |
      '#8e725e' |
      '#8f4074' |
      '#8f6453' |
      '#8f6a54' |
      '#8f6b51' |
      '#8f9496' |
      '#8f989e' |
      '#8fbedb' |
      '#9028e0' |
      '#9156b7' |
      '#916140' |
      '#917524' |
      '#917dbc' |
      '#9180ff' |
      '#919191' |
      '#919193' |
      '#91999f' |
      '#923f00' |
      '#933434' |
      '#935e3e' |
      '#93603b' |
      '#93695a' |
      '#937237' |
      '#93a2aa' |
      '#93ced6' |
      '#93e67f' |
      '#9450e0' |
      '#947151' |
      '#94989b' |
      '#94d82a' |
      '#95a55b' |
      '#961623' |
      '#962c2c' |
      '#96877d' |
      '#96a2aa' |
      '#96a7a8' |
      '#96b269' |
      '#9729cc' |
      '#979797' |
      '#97a3a2' |
      '#97b113' |
      '#991d1d' |
      '#994360' |
      '#994848' |
      '#995024' |
      '#996254' |
      '#9970c4' |
      '#997361' |
      '#998a91' |
      '#999' |
      '#999a9c' |
      '#99cff6' |
      '#9aa0a5' |
      '#9aabaf' |
      '#9aca0a' |
      '#9b5c54' |
      '#9b7861' |
      '#9b9596' |
      '#9c2c1b' |
      '#9c323c' |
      '#9c3900' |
      '#9c5100' |
      '#9c6525' |
      '#9c7052' |
      '#9ca84d' |
      '#9caaaf' |
      '#9db730' |
      '#9dd7ff' |
      '#9e6eeb' |
      '#9e7658' |
      '#9e958f' |
      '#9ec1ff' |
      '#9f7dcc' |
      '#9fa1a6' |
      '#9fc427' |
      '#9fe4ff' |
      '#B3660D' |
      '#CE1124' |
      '#DE7F11' |
      '#E2D8C7' |
      '#EEE' |
      '#a01a5d' |
      '#a0cfeb' |
      '#a13e14' |
      '#a16745' |
      '#a1acb3' |
      '#a1b8c7' |
      '#a1d8f2' |
      '#a29b95' |
      '#a2cbdb' |
      '#a35cff' |
      '#a36c43' |
      '#a37352' |
      '#a374b8' |
      '#a37d64' |
      '#a37e3d' |
      '#a37f6a' |
      '#a38982' |
      '#a3bf2c' |
      '#a3e66f' |
      '#a4b3b2' |
      '#a5000c' |
      '#a51000' |
      '#a5203c' |
      '#a52355' |
      '#a53838' |
      '#a5627a' |
      '#a57b5e' |
      '#a59872' |
      '#a59a7c' |
      '#a5a5a5' |
      '#a5a7a9' |
      '#a67acc' |
      '#a6876c' |
      '#a6aeb0' |
      '#a6aeb2' |
      '#a80038' |
      '#a8203b' |
      '#a8521a' |
      '#a86332' |
      '#a8693f' |
      '#a8734f' |
      '#a87451' |
      '#a87654' |
      '#a87d5d' |
      '#a88673' |
      '#a8a08d' |
      '#a8b2ba' |
      '#a8d600' |
      '#a93feb' |
      '#a9afb8' |
      '#a9b5ae' |
      '#aa1d39' |
      '#aa1f65' |
      '#aa3369' |
      '#aa7d5e' |
      '#aaacad' |
      '#aab5bc' |
      '#ab2d1f' |
      '#ab7dcc' |
      '#abc2c6' |
      '#acafb5' |
      '#acb8bf' |
      '#ace1ef' |
      '#ad2727' |
      '#ad4040' |
      '#ad6c3f' |
      '#ad8366' |
      '#adb5bc' |
      '#adea73' |
      '#ae3ffd' |
      '#aebabf' |
      '#aec470' |
      '#af1734' |
      '#af2b2b' |
      '#af5a31' |
      '#af7146' |
      '#af7751' |
      '#af921b' |
      '#afcddb' |
      '#b0b8b8' |
      '#b0bcc1' |
      '#b0bdc6' |
      '#b0bfc1' |
      '#b17f4a' |
      '#b1babf' |
      '#b1bcc4' |
      '#b21725' |
      '#b23838' |
      '#b28769' |
      '#b2b2b2' |
      '#b2b6b8' |
      '#b2c1c0' |
      '#b2d921' |
      '#b2f25e' |
      '#b35454' |
      '#b3682a' |
      '#b3690e' |
      '#b371ec' |
      '#b37b47' |
      '#b386e2' |
      '#b39066' |
      '#b3b3b3' |
      '#b3bdc4' |
      '#b3c0c4' |
      '#b46137' |
      '#b47d56' |
      '#b4b6b9' |
      '#b4d7ee' |
      '#b4e7ed' |
      '#b54152' |
      '#b5607c' |
      '#b58360' |
      '#b59267' |
      '#b5b5b5' |
      '#b5de24' |
      '#b5f478' |
      '#b69467' |
      '#b6acaa' |
      '#b6c0c6' |
      '#b6c1d1' |
      '#b6c4a7' |
      '#b6ef00' |
      '#b6fff1' |
      '#b70000' |
      '#b70b0b' |
      '#b71c3a' |
      '#b77e58' |
      '#b7805c' |
      '#b78300' |
      '#b7925e' |
      '#b79918' |
      '#b7b198' |
      '#b8331e' |
      '#b85d7b' |
      '#b86acb' |
      '#b86e5d' |
      '#b8c2c4' |
      '#b95a1e' |
      '#b9b9bf' |
      '#b9c1c6' |
      '#ba0028' |
      '#ba454b' |
      '#ba5327' |
      '#ba573f' |
      '#ba6b24' |
      '#ba8443' |
      '#ba9372' |
      '#bab6b6' |
      '#bacad3' |
      '#badede' |
      '#bbc3c7' |
      '#bbecff' |
      '#bc2e2e' |
      '#bc600d' |
      '#bc6464' |
      '#bc715f' |
      '#bc7e22' |
      '#bc845e' |
      '#bc9342' |
      '#bcbcbc' |
      '#bcc0c1' |
      '#bcc2cc' |
      '#bd80ff' |
      '#bd8800' |
      '#bec0c6' |
      '#bec6c9' |
      '#bedd4b' |
      '#bf7b90' |
      '#bf906c' |
      '#bf9173' |
      '#bfae6e' |
      '#bfb3a4' |
      '#bfbebe' |
      '#bfe5e8' |
      '#bfffab' |
      '#c0773b' |
      '#c09300' |
      '#c09b5a' |
      '#c10259' |
      '#c1875d' |
      '#c19a61' |
      '#c1c4cb' |
      '#c1c9c9' |
      '#c1c9cb' |
      '#c2185b' |
      '#c28200' |
      '#c28d69' |
      '#c28fef' |
      '#c2aca1' |
      '#c2f8ff' |
      '#c47116' |
      '#c47500' |
      '#c49a45' |
      '#c4c5c6' |
      '#c4ccce' |
      '#c4ced6' |
      '#c5ccd6' |
      '#c5cdd3' |
      '#c5cfd3' |
      '#c5d0d8' |
      '#c5d4d8' |
      '#c65c3c' |
      '#c6a397' |
      '#c6bbb3' |
      '#c6cedb' |
      '#c76a00' |
      '#c79127' |
      '#c79cff' |
      '#c7b299' |
      '#c7b37f' |
      '#c7b500' |
      '#c7c7c7' |
      '#c7d3d8' |
      '#c7d7d7' |
      '#c7e755' |
      '#c7e86f' |
      '#c7e8eb' |
      '#c8313e' |
      '#c8b100' |
      '#c8d0d6' |
      '#c8d2da' |
      '#c8d9d8' |
      '#c9150d' |
      '#c9243c' |
      '#c94747' |
      '#c98659' |
      '#c98e52' |
      '#c99ff7' |
      '#c9ac1c' |
      '#c9ae81' |
      '#c9c9c9' |
      '#c9d1d3' |
      '#cad5dd' |
      '#cb2c41' |
      '#cb8d44' |
      '#cba7f9' |
      '#cbd1d6' |
      '#cbd8de' |
      '#cc2e45' |
      '#cc3636' |
      '#cc4c5e' |
      '#cc6060' |
      '#cc7f2b' |
      '#cc9132' |
      '#cc996e' |
      '#cc9a72' |
      '#cc9b76' |
      '#ccc' |
      '#cccfd4' |
      '#cdad56' |
      '#cdecfc' |
      '#ce0f00' |
      '#ce1126' |
      '#ce114b' |
      '#ce344a' |
      '#ce95a0' |
      '#ce9915' |
      '#ce9c7a' |
      '#cecece' |
      '#ced74d' |
      '#cedae0' |
      '#cedbd5' |
      '#ceff80' |
      '#cf4350' |
      '#cf4d4d' |
      '#cf9364' |
      '#cf9d78' |
      '#cfdae8' |
      '#d0d0d0' |
      '#d0d18b' |
      '#d0d5d8' |
      '#d19500' |
      '#d1c5b5' |
      '#d1d1d1' |
      '#d1dbe3' |
      '#d1dce6' |
      '#d2cfcf' |
      '#d2d3d5' |
      '#d2d8d9' |
      '#d33777' |
      '#d33b23' |
      '#d35454' |
      '#d39762' |
      '#d3976e' |
      '#d3b226' |
      '#d3d3d3' |
      '#d3ff75' |
      '#d46c8f' |
      '#d47f6c' |
      '#d4daf4' |
      '#d51c46' |
      '#d52b1e' |
      '#d5dfff' |
      '#d5ff83' |
      '#d64553' |
      '#d66b3c' |
      '#d68f00' |
      '#d6a57c' |
      '#d6d6d6' |
      '#d6dfe3' |
      '#d6eef0' |
      '#d7d16f' |
      '#d7dadb' |
      '#d82b45' |
      '#d8544a' |
      '#d8681d' |
      '#d87512' |
      '#d8a322' |
      '#d8a941' |
      '#d8d2b8' |
      '#d8d8d8' |
      '#d8dfeb' |
      '#d8e0e0' |
      '#d93d3d' |
      '#d97448' |
      '#d99634' |
      '#d99b57' |
      '#d9a000' |
      '#d9a559' |
      '#d9e3e8' |
      '#da121a' |
      '#da5b52' |
      '#dadee0' |
      '#dae3ea' |
      '#dae4ea' |
      '#dae5ef' |
      '#db3557' |
      '#db802b' |
      '#db8823' |
      '#db9523' |
      '#db9e75' |
      '#dba780' |
      '#dbb046' |
      '#dbb471' |
      '#dbcdaa' |
      '#dbf763' |
      '#dc241f' |
      '#dce1e5' |
      '#dce5e5' |
      '#dda85f' |
      '#ddb199' |
      '#ddd' |
      '#ddd243' |
      '#ddd3ca' |
      '#dddad5' |
      '#dde8e3' |
      '#ddeaf2' |
      '#dedfe0' |
      '#dfcea3' |
      '#dfdfdf' |
      '#dfe9eb' |
      '#dfe9ef' |
      '#dfecf4' |
      '#dff4f4' |
      '#e07297' |
      '#e07e1e' |
      '#e08672' |
      '#e08828' |
      '#e0a372' |
      '#e0a763' |
      '#e0ac68' |
      '#e0ac7e' |
      '#e0bb86' |
      '#e0dac6' |
      '#e0e1e5' |
      '#e17c5b' |
      '#e1e8ed' |
      '#e1eaf2' |
      '#e1ebef' |
      '#e1edf5' |
      '#e24b4b' |
      '#e2596c' |
      '#e26a3b' |
      '#e27c17' |
      '#e2af23' |
      '#e2c69e' |
      '#e2ccaf' |
      '#e2d8c7' |
      '#e2e2e2' |
      '#e2e9ed' |
      '#e2f0f2' |
      '#e3a300' |
      '#e3a93d' |
      '#e4e7ea' |
      '#e4eef7' |
      '#e5bc5e' |
      '#e5be7a' |
      '#e5c900' |
      '#e5c9bd' |
      '#e5dec1' |
      '#e5e5e5' |
      '#e68a00' |
      '#e6b796' |
      '#e6b858' |
      '#e6d0a3' |
      '#e6e6e6' |
      '#e6eded' |
      '#e6eff4' |
      '#e7a74f' |
      '#e8491f' |
      '#e84d88' |
      '#e86097' |
      '#e8662d' |
      '#e88f27' |
      '#e8a30e' |
      '#e8b188' |
      '#e8e1d6' |
      '#e8e8e8' |
      '#e8ecef' |
      '#e8edef' |
      '#e8f94b' |
      '#e9841a' |
      '#e9c243' |
      '#e9edf2' |
      '#e9f3fa' |
      '#ea83a3' |
      '#ea9f07' |
      '#eaac6e' |
      '#eab2bb' |
      '#eabc92' |
      '#eac102' |
      '#eae7e4' |
      '#eba352' |
      '#ebbc99' |
      '#ebc463' |
      '#ebf2f2' |
      '#ec6430' |
      '#ecffad' |
      '#ed1c24' |
      '#ed4040' |
      '#ed4c5c' |
      '#ed5181' |
      '#ed77a8' |
      '#eda454' |
      '#edba53' |
      '#edd8b4' |
      '#ede0d1' |
      '#ede2d1' |
      '#edf4f9' |
      '#edff54' |
      '#eef8fb' |
      '#ef4d3c' |
      '#ef4e16' |
      '#ef5350' |
      '#ef8a45' |
      '#ef9b92' |
      '#efd57f' |
      '#efd8b1' |
      '#efdec2' |
      '#efeded' |
      '#eff6f7' |
      '#efffd9' |
      '#f0154f' |
      '#f085a9' |
      '#f09985' |
      '#f0ae11' |
      '#f0c0c6' |
      '#f0f4f5' |
      '#f14e3a' |
      '#f15744' |
      '#f15a61' |
      '#f16a65' |
      '#f1bf31' |
      '#f1e7dc' |
      '#f25151' |
      '#f26b8c' |
      '#f27a52' |
      '#f29a2e' |
      '#f2b200' |
      '#f2b5b5' |
      '#f2bc97' |
      '#f2c19b' |
      '#f2c4a5' |
      '#f2cb7d' |
      '#f2d2ac' |
      '#f2eacc' |
      '#f2ece3' |
      '#f2f1f0' |
      '#f2f2f2' |
      '#f33' |
      '#f361f5' |
      '#f3813b' |
      '#f3f7fa' |
      '#f3ffd2' |
      '#f42f4c' |
      '#f46767' |
      '#f46c6c' |
      '#f4a19a' |
      '#f4a24e' |
      '#f4bc58' |
      '#f4d3ae' |
      '#f4d4a5' |
      '#f4dc9f' |
      '#f55' |
      '#f5a300' |
      '#f5ce3e' |
      '#f5d1ac' |
      '#f5d402' |
      '#f5f0ae' |
      '#f5f5f5' |
      '#f65500' |
      '#f66' |
      '#f6b40e' |
      '#f6c799' |
      '#f6da77' |
      '#f78d8d' |
      '#f7a4a4' |
      '#f7b600' |
      '#f7c600' |
      '#f7e017' |
      '#f7f2df' |
      '#f8b100' |
      '#f8d048' |
      '#f8d317' |
      '#f8db7d' |
      '#f8ecc5' |
      '#f9b04e' |
      '#f9b978' |
      '#f9cf02' |
      '#f9db17' |
      '#f9dd16' |
      '#f9dd19' |
      '#f9eeb6' |
      '#f9f3d9' |
      '#f9f9f9' |
      '#fabf49' |
      '#fad85c' |
      '#fb4f00' |
      '#fbb287' |
      '#fbbf67' |
      '#fbd399' |
      '#fc0' |
      '#fc6' |
      '#fc9100' |
      '#fc97b2' |
      '#fca9c9' |
      '#fcb334' |
      '#fcbe10' |
      '#fcd116' |
      '#fcd856' |
      '#fcfcfa' |
      '#fd0' |
      '#fd9d33' |
      '#fdb73e' |
      '#fdce12' |
      '#fddfb3' |
      '#fdeeff' |
      '#fdf516' |
      '#fdffb8' |
      '#fed0ac' |
      '#fee0af' |
      '#fee790' |
      '#fee801' |
      '#fee8d8' |
      '#fef500' |
      '#ff0' |
      '#ff2449' |
      '#ff2a2a' |
      '#ff2c68' |
      '#ff4085' |
      '#ff435e' |
      '#ff4848' |
      '#ff503e' |
      '#ff506e' |
      '#ff5263' |
      '#ff5760' |
      '#ff5a79' |
      '#ff639b' |
      '#ff6473' |
      '#ff7000' |
      '#ff7033' |
      '#ff717f' |
      '#ff7190' |
      '#ff71d0' |
      '#ff73c0' |
      '#ff78a5' |
      '#ff78b5' |
      '#ff7e27' |
      '#ff8080' |
      '#ff81ab' |
      '#ff8736' |
      '#ff8b00' |
      '#ff8e66' |
      '#ff927f' |
      '#ff9430' |
      '#ff9463' |
      '#ff94a4' |
      '#ff99ad' |
      '#ff99b6' |
      '#ff9a08' |
      '#ff9c70' |
      '#ff9d27' |
      '#ff9d33' |
      '#ff9e3d' |
      '#ff9ee1' |
      '#ffa4a4' |
      '#ffa599' |
      '#ffa6af' |
      '#ffab41' |
      '#ffabed' |
      '#ffb300' |
      '#ffb700' |
      '#ffb77b' |
      '#ffbc00' |
      '#ffbe5c' |
      '#ffbf1f' |
      '#ffbf3e' |
      '#ffc17a' |
      '#ffc200' |
      '#ffc267' |
      '#ffc294' |
      '#ffc44a' |
      '#ffc466' |
      '#ffc543' |
      '#ffc5d3' |
      '#ffc6b5' |
      '#ffc78a' |
      '#ffc7ce' |
      '#ffc800' |
      '#ffc861' |
      '#ffc900' |
      '#ffc942' |
      '#ffc95c' |
      '#ffca28' |
      '#ffce31' |
      '#ffd05a' |
      '#ffd170' |
      '#ffd200' |
      '#ffd252' |
      '#ffd2df' |
      '#ffd41f' |
      '#ffd452' |
      '#ffd45c' |
      '#ffd582' |
      '#ffd664' |
      '#ffd68d' |
      '#ffd6bb' |
      '#ffd7e4' |
      '#ffd83c' |
      '#ffd85c' |
      '#ffd86c' |
      '#ffd93b' |
      '#ffda87' |
      '#ffdb75' |
      '#ffdd67' |
      '#ffdd7d' |
      '#ffdf85' |
      '#ffdf99' |
      '#ffe000' |
      '#ffe0b5' |
      '#ffe1bd' |
      '#ffe299' |
      '#ffe2b3' |
      '#ffe394' |
      '#ffe54d' |
      '#ffe606' |
      '#ffe62e' |
      '#ffe655' |
      '#ffe6e8' |
      '#ffe6ea' |
      '#ffe75a' |
      '#ffe76e' |
      '#ffe791' |
      '#ffe8a6' |
      '#ffe8bb' |
      '#ffe8dc' |
      '#ffe9ab' |
      '#ffea92' |
      '#ffebb8' |
      '#ffebd2' |
      '#ffec40' |
      '#ffecd6' |
      '#ffeee2' |
      '#fff033' |
      '#fff080' |
      '#fff0f0' |
      '#fff0f3' |
      '#fff3e3' |
      '#fff3f7' |
      '#fff652' |
      '#fff6d1' |
      '#fff6d7' |
      '#fff7ab' |
      '#fff8d6' |
      '#fffb80' |
      '#fffbe9' |
      '#ffffc4' |
      '#ffffd4' |
      '#ffffff';

    type backgroundType = 'circle' | 'rect' | 'button';

    type colorsType = Record<iconColors, string>;

    type positionType = 'top' | 'bottom' | 'right' | 'left' |
      'top_right' | 'top_left' | 'bottom_right' | 'bottom_left';

    type backgroundTypeObj = {
      type?: backgroundType;
      color?: string;
      radius?: number;
      borderRadius?: number;
    };

    type badgeTypeObj = {
      value?: number | string;
      fontSize?: string;
      position?: positionType;
      color?: string;
      colors: colorsType;
      backgroundColor?: string;
      radius?: number;
    };

    interface IconProps {
      name: iconNames;
      width?: number;
      height?: number;
      color?: string;
      colors?: colorsType;
      stroke?: number;
      background?: backgroundType | backgroundTypeObj;
      badge?: number | string | badgeTypeObj;
    }

    const Icon: (props: IconProps & SvgProps & AdditionalProps) => ReactNode;

    export { iconNames };
    export default Icon;
}
